# Creating wildfire dataset for any country using global satellite data #
## We are using country India as our target country  in this example ##

## Data Collection ##
- Please Visit https://firms.modaps.eosdis.nasa.gov/download/ to download both MODIS (2000-2020) and VIIRS (2012-2020) datasets based on each country wildfire data
  - MODIS - https://firms.modaps.eosdis.nasa.gov/country/
  - VIIRS - https://firms.modaps.eosdis.nasa.gov/country/
  - Active Fire (24 Hours, 48 Hours, 7 days)-  https://firms.modaps.eosdis.nasa.gov/usfs/active_fire/

<div style="max-width:400px;">
    <img src="https://github.com/prodramp/wildfire/blob/main/images/disclaimer.png?raw=true" size="400px"/>
</div>

In [1]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
import random
InteractiveShell.ast_node_interactivity = "all"
import os
from datetime import datetime
import plotly.express as px
import glob
from tqdm import tqdm
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 8E69-9D46

 Directory of C:\Users\Sawan\Documents

14-03-2023  11:36    <DIR>          .
14-03-2023  08:59    <DIR>          ..
14-03-2023  11:36    <DIR>          .ipynb_checkpoints
14-03-2023  11:35    <DIR>          dataset
07-03-2023  14:43    <DIR>          OneNote Notebooks
07-03-2023  00:19    <DIR>          Python Scripts
07-03-2023  14:49            13,795 Untitled.ipynb
14-03-2023  11:36           319,350 wildfire_data_creation-nepal-Copy1.ipynb
14-03-2023  11:36           319,350 wildfire_data_creation-nepal.ipynb
14-03-2023  11:19           276,236 Wildfire_data_creation.ipynb
               4 File(s)        928,731 bytes
               6 Dir(s)  56,335,073,280 bytes free

In [3]:
%cd dataset

C:\Users\Sawan\Documents\dataset

In [4]:
%cd dataset

[WinError 2] The system cannot find the file specified: 'dataset'
C:\Users\Sawan\Documents\dataset

In [5]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 8E69-9D46

 Directory of C:\Users\Sawan\Documents\dataset

14-03-2023  11:35    <DIR>          .
14-03-2023  11:36    <DIR>          ..
13-03-2023  21:08    <DIR>          modis
14-03-2023  11:35         2,855,490 nepal_daily_fire_2000_2020.csv
13-03-2023  21:20    <DIR>          viirs_snnp
               1 File(s)      2,855,490 bytes
               4 Dir(s)  56,324,587,520 bytes free

In [7]:
all_csv_files = glob.glob('C:/Users/Sawan/Documents/dataset/**/*.csv', recursive=True)

In [8]:
all_csv_files

['C:/Users/Sawan/Documents/dataset\\nepal_daily_fire_2000_2020.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Afghanistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Albania.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Algeria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Angola.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Argentina.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Armenia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Australia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Austria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Azerbaijan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bahamas.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bangladesh.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Belarus.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Belgium.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Belize.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Benin.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bhutan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bolivia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bosnia_and_Herzegovina.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Botswana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Brazil.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bulgaria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Burkina_Faso.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Burundi.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Cambodia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Cameroon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Canada.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Central_African_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Chad.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Chile.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_China.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Colombia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Costa_Rica.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Cote_d_Ivoire.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Croatia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Cuba.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Curacao.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Cyprus.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Czech_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Democratic_Republic_of_the_Congo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Dem_Rep_Korea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Dominican_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Ecuador.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Egypt.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_El_Salvador.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Equatorial_Guinea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Eritrea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Ethiopia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Fiji.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_France.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_French_Guiana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_French_Polynesia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Gabon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Georgia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Germany.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Ghana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Greece.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Guatemala.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Guinea-Bissau.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Guinea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Guyana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Haiti.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Heard_I_and_McDonald_Islands.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Honduras.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Hungary.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Indonesia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Iran.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Iraq.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Israel.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Italy.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Jamaica.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Japan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Jordan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Kazakhstan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Kenya.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Kosovo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Kuwait.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Kyrgyzstan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Lao_PDR.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Lebanon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Liberia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Libya.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Luxembourg.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Macedonia_Former_Yugoslav_Republic_of.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Madagascar.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Malawi.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Malaysia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Maldives.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Mali.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Mauritania.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Mauritius.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Mexico.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Moldova.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Montenegro.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Montserrat.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Morocco.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Mozambique.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Myanmar.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Namibia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Netherlands.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_New_Caledonia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_New_Zealand.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Nicaragua.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Niger.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Nigeria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Oman.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Pakistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Palestine.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Panama.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Papua_New_Guinea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Paraguay.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Peru.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Philippines.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Poland.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Portugal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Puerto_Rico.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Qatar.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Republic_of_Congo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Republic_of_Korea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Reunion.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Romania.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Russian_Federation.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Rwanda.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Samoa.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Saudi_Arabia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Senegal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Serbia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Sierra_Leone.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Slovakia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Solomon_Islands.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Somalia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_South_Africa.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_South_Sudan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Spain.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Sri_Lanka.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Sudan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Suriname.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Swaziland.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Syria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Taiwan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Tajikistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Tanzania.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Thailand.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_The_Gambia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Timor-Leste.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Togo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Trinidad_and_Tobago.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Turkey.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Turkmenistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Uganda.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Ukraine.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_United_Arab_Emirates.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_United_Kingdom.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_United_States.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Uruguay.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Uzbekistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Vanuatu.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Venezuela.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Vietnam.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Yemen.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Zambia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Zimbabwe.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Afghanistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Albania.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Algeria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Andorra.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Angola.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Argentina.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Armenia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Australia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Austria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Azerbaijan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bahamas.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bangladesh.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Barbados.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Belarus.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Belgium.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Belize.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Benin.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bhutan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bolivia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bosnia_and_Herzegovina.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Botswana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Brazil.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Brunei_Darussalam.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bulgaria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Burkina_Faso.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Burundi.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cambodia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cameroon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Canada.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cape_Verde.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Central_African_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Chad.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Chile.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_China.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Colombia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Comoros.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Costa_Rica.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cote_d_Ivoire.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Croatia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cuba.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Curacao.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cyprus.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Czech_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Democratic_Republic_of_the_Congo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Dem_Rep_Korea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Denmark.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Djibouti.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Dominica.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Dominican_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Ecuador.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Egypt.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_El_Salvador.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Equatorial_Guinea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Eritrea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Estonia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Ethiopia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Falkland_Islands.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Fiji.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Finland.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_France.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_French_Guiana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_French_Polynesia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Gabon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Georgia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Germany.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Ghana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Greece.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Greenland.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guadeloupe.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guam.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guatemala.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guinea-Bissau.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guinea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guyana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Haiti.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Honduras.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Hong_Kong.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Hungary.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Indonesia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Iran.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Iraq.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Ireland.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Israel.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Italy.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Jamaica.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Japan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Jordan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Kazakhstan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Kenya.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Kosovo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Kuwait.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Kyrgyzstan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Lao_PDR.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Latvia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Lebanon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Lesotho.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Liberia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Libya.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Lithuania.csv',

In [9]:
len(all_csv_files)

6636

In [10]:
type(all_csv_files)

list

In [ ]:
# all_us_files = list(filter(lambda k: 'United_States' in k, all_csv_file))

In [11]:
all_india_files = list(filter(lambda k: 'India' in k, all_csv_files))

In [12]:
all_india_files

['C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2002\\modis_2002_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2003\\modis_2003_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2004\\modis_2004_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2005\\modis_2005_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2006\\modis_2006_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2007\\modis_2007_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2008\\modis_2008_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2009\\modis_2009_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2010\\modis_2010_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2011\\modis_2011_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2012\\modis_2012_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2013\\modis_2013_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2014\\modis_2014_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2015\\modis_2015_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2016\\modis_2016_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2017\\modis_2017_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2018\\modis_2018_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2019\\modis_2019_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2020\\modis_2020_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2021\\modis_2021_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2012\\viirs-snpp_2012_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2013\\viirs-snpp_2013_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2014\\viirs-snpp_2014_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2015\\viirs-snpp_2015_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2016\\viirs-snpp_2016_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2017\\viirs-snpp_2017_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2018\\viirs-snpp_2018_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2019\\viirs-snpp_2019_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2020\\viirs-snpp_2020_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2021\\viirs-snpp_2021_India.csv']

In [13]:
all_india_files = list(filter(lambda k: 'India.csv' in k, all_csv_files))

In [14]:
all_india_files

['C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2002\\modis_2002_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2003\\modis_2003_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2004\\modis_2004_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2005\\modis_2005_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2006\\modis_2006_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2007\\modis_2007_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2008\\modis_2008_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2009\\modis_2009_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2010\\modis_2010_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2011\\modis_2011_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2012\\modis_2012_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2013\\modis_2013_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2014\\modis_2014_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2015\\modis_2015_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2016\\modis_2016_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2017\\modis_2017_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2018\\modis_2018_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2019\\modis_2019_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2020\\modis_2020_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2021\\modis_2021_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2012\\viirs-snpp_2012_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2013\\viirs-snpp_2013_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2014\\viirs-snpp_2014_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2015\\viirs-snpp_2015_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2016\\viirs-snpp_2016_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2017\\viirs-snpp_2017_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2018\\viirs-snpp_2018_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2019\\viirs-snpp_2019_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2020\\viirs-snpp_2020_India.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2021\\viirs-snpp_2021_India.csv']

In [15]:
df_viirs = pd.read_csv('C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2020\\viirs-snpp_2020_India.csv')

C:\Users\Sawan\AppData\Local\Temp\ipykernel_17800\4202710759.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_viirs = pd.read_csv('C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2020\\viirs-snpp_2020_India.csv')

In [16]:
df_viirs = pd.read_csv('C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2020\\viirs-snpp_2020_India.csv', low_memory=False)

In [17]:
df_viirs

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight,type
0,17.903887,82.763351,339.89,0.51,0.66,2020-01-01,655,N,VIIRS,n,1,291.53,7.62,D,0
1,20.164076,85.090897,329.90,0.33,0.55,2020-01-01,655,N,VIIRS,n,1,295.11,2.08,D,0
2,21.426310,83.864632,333.79,0.37,0.58,2020-01-01,656,N,VIIRS,n,1,291.76,3.38,D,0
3,22.281143,86.837601,325.83,0.47,0.48,2020-01-01,656,N,VIIRS,n,1,293.52,2.98,D,0
4,22.785248,87.835228,328.26,0.40,0.44,2020-01-01,656,N,VIIRS,n,1,295.14,2.49,D,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482820,11.809664,77.924614,303.10,0.39,0.36,2020-12-31,2024,N,VIIRS,n,1,292.79,0.93,0,2
482821,14.282310,75.594276,303.40,0.41,0.37,2020-12-31,2024,N,VIIRS,n,1,289.81,0.53,0,0
482822,13.217650,80.055916,301.80,0.45,0.39,2020-12-31,2024,N,VIIRS,n,1,291.41,0.40,0,0
482823,14.026445,74.590767,312.80,0.44,0.38,2020-12-31,2024,N,VIIRS,n,1,291.73,1.09,0,0
482824,33.442413,74.189064,299.31,0.78,0.78,2020-12-31,2154,N,VIIRS,n,1,276.28,1.10,0,0

In [18]:
df_viirs['satellite'].unique()

array(['N'], dtype=object)

In [19]:
df_viirs['instrument'].unique()

array(['VIIRS'], dtype=object)

In [20]:
type(df_viirs.confidence[0])

str

In [21]:
isinstance(df_viirs.confidence[0], str)

True

In [22]:
df_viirs.confidence.unique()

array(['n', 'l', 'h'], dtype=object)

In [26]:
df_modis = pd.read_csv( 'C:/Users/Sawan/Documents/dataset\\modis\\2020\\modis_2020_India.csv')

In [27]:
df_modis

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,28.1282,96.9943,301.4,1.7,1.3,2020-01-01,357,Terra,MODIS,40,6.03,278.8,15.3,D,0
1,33.1827,74.0774,301.5,1.5,1.2,2020-01-01,534,Terra,MODIS,48,6.03,280.6,12.3,D,0
2,30.0068,80.6242,300.6,1.1,1.1,2020-01-01,535,Terra,MODIS,38,6.03,278.7,9.1,D,0
3,28.9858,79.6159,304.1,1.1,1.0,2020-01-01,535,Terra,MODIS,58,6.03,288.8,6.4,D,0
4,30.1529,80.2387,301.9,1.1,1.0,2020-01-01,535,Terra,MODIS,41,6.03,274.5,7.3,D,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76016,16.1899,75.4502,300.9,1.7,1.3,2020-12-31,1738,Terra,MODIS,35,6.03,289.5,9.0,N,0
76017,21.1035,72.6365,308.7,1.3,1.1,2020-12-31,1740,Terra,MODIS,75,6.03,291.7,13.7,N,2
76018,22.7952,86.2129,317.9,1.6,1.3,2020-12-31,2024,Aqua,MODIS,96,6.03,288.6,37.3,N,2
76019,20.9639,85.1806,306.5,1.5,1.2,2020-12-31,2025,Aqua,MODIS,68,6.03,289.9,16.4,N,2
76020,20.9664,85.1664,300.7,1.5,1.2,2020-12-31,2025,Aqua,MODIS,32,6.03,288.8,9.7,N,2

In [28]:
df_modis['satellite'].unique()

array(['Terra', 'Aqua'], dtype=object)

In [29]:
df_modis['instrument'].unique()

array(['MODIS'], dtype=object)

In [30]:
type(df_modis['confidence'][0])

numpy.int64

In [31]:
df_modis['confidence'].unique()

array([ 40,  48,  38,  58,  41,  57,  76,  51,   0,  64,  67,  65,  75,
        69,  54,  50,  49,  61,  47,  66,  44,  52,  60,  68,  59,  72,
        56,  63, 100,  79,  55,  19,  34,  88,  74,  77,  32,  71,  46,
        86,  70,  78,  85,  15,  26,  39,  33,  36,  37,  62,  73,  17,
        91,  87,  13,  29,  27,  45,  21,  42,  28,  84,  90,  82,  89,
        12,  80,  35,  53,  43,  83,  24,  92,  30,  31,  99,  81,  23,
        18,  20,  25,  10,  96,  93,  22,  97,  95,   7,  94,  14,  16,
         8,  11,   4,  98,   5,   2,   9,   6,   1,   3], dtype=int64)

In [33]:
# Taken this idea from the H2O.ai wild fire competition github repo and changed it meet the local need
rows = []
fire_df = []
row_sum = 0
for f in tqdm(all_india_files):
    df = pd.read_csv(f, parse_dates=['acq_time'], low_memory=False) 
    csv_name = f.split('/')[-1]
    row = [
        f, csv_name, df.shape[0], df.shape[1], df.acq_date.min(), df.acq_date.max(),
        df.satellite.unique(), df.instrument.max(), df.version.max(),
        df.latitude.nunique(), df.longitude.nunique(),
        df.confidence.nunique(), df.satellite.nunique(), df.acq_date.nunique()
    ]
    if isinstance(df.confidence[0], str):
        df.confidence = df.confidence.replace({'l': 0, 'n': 50, 'h': 100})
    rows.append(row)
    row_sum = row_sum + df.shape[0]
    fire_df.append(df)
cols = [
    'path', 'csv', 'rows', 'cols', 'start', 'end',
    'satellite', 'instrument', 'version',
    'lats', 'lons', 'confs', 'sats', 'days'
]
filestats = pd.DataFrame(rows, columns=cols)
filestats.sort_values(by=['start', 'instrument'])
print("Total Rows: " + str(row_sum))

100%|██████████████████████████████████████████████████████████████████████████████████| 32/32 [00:24<00:00,  1.33it/s]

,path,csv,rows,cols,start,end,satellite,instrument,version,lats,lons,confs,sats,days
0,C:/Users/Sawan/Documents/dataset\modis\2000\mo...,dataset\modis\2000\modis_2000_India.csv,1407,15,2000-11-01,2000-12-31,[Terra],MODIS,6.20,1385,1388,89,1,61
1,C:/Users/Sawan/Documents/dataset\modis\2001\mo...,dataset\modis\2001\modis_2001_India.csv,18719,15,2001-01-01,2001-12-31,[Terra],MODIS,6.20,17335,17309,97,1,328
2,C:/Users/Sawan/Documents/dataset\modis\2002\mo...,dataset\modis\2002\modis_2002_India.csv,26751,15,2002-01-01,2002-12-31,"[Terra, Aqua]",MODIS,6.20,21390,21656,99,2,340
3,C:/Users/Sawan/Documents/dataset\modis\2003\mo...,dataset\modis\2003\modis_2003_India.csv,56091,15,2003-01-01,2003-12-31,"[Terra, Aqua]",MODIS,6.20,44006,44811,98,2,354
4,C:/Users/Sawan/Documents/dataset\modis\2004\mo...,dataset\modis\2004\modis_2004_India.csv,64725,15,2004-01-01,2004-12-31,"[Terra, Aqua]",MODIS,6.20,50471,50699,100,2,360
5,C:/Users/Sawan/Documents/dataset\modis\2005\mo...,dataset\modis\2005\modis_2005_India.csv,63485,15,2005-01-01,2005-12-31,"[Terra, Aqua]",MODIS,6.20,47858,48361,98,2,354
6,C:/Users/Sawan/Documents/dataset\modis\2006\mo...,dataset\modis\2006\modis_2006_India.csv,65980,15,2006-01-01,2006-12-31,"[Terra, Aqua]",MODIS,6.20,49947,50427,100,2,360
7,C:/Users/Sawan/Documents/dataset\modis\2007\mo...,dataset\modis\2007\modis_2007_India.csv,75320,15,2007-01-01,2007-12-31,"[Terra, Aqua]",MODIS,6.20,56335,55652,101,2,362
8,C:/Users/Sawan/Documents/dataset\modis\2008\mo...,dataset\modis\2008\modis_2008_India.csv,70913,15,2008-01-01,2008-12-31,"[Terra, Aqua]",MODIS,6.20,53565,53909,100,2,356
9,C:/Users/Sawan/Documents/dataset\modis\2009\mo...,dataset\modis\2009\modis_2009_India.csv,90236,15,2009-01-01,2009-12-31,"[Terra, Aqua]",MODIS,6.20,65475,65934,100,2,360
10,C:/Users/Sawan/Documents/dataset\modis\2010\mo...,dataset\modis\2010\modis_2010_India.csv,76668,15,2010-01-01,2010-12-31,"[Terra, Aqua]",MODIS,6.20,55334,58311,100,2,365
11,C:/Users/Sawan/Documents/dataset\modis\2011\mo...,dataset\modis\2011\modis_2011_India.csv,72372,15,2011-01-01,2011-12-31,"[Terra, Aqua]",MODIS,6.20,54948,55287,101,2,357
12,C:/Users/Sawan/Documents/dataset\modis\2012\mo...,dataset\modis\2012\modis_2012_India.csv,93150,15,2012-01-01,2012-12-31,"[Terra, Aqua]",MODIS,6.20,67114,67502,101,2,363
22,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2012\viirs-snpp_2012_India.csv,579467,15,2012-01-20,2012-12-31,[N],VIIRS,1.00,548355,490948,3,1,346
13,C:/Users/Sawan/Documents/dataset\modis\2013\mo...,dataset\modis\2013\modis_2013_India.csv,71173,15,2013-01-01,2013-12-31,"[Terra, Aqua]",MODIS,6.20,53622,54202,101,2,361
23,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2013\viirs-snpp_2013_India.csv,489143,15,2013-01-01,2013-12-31,[N],VIIRS,1.00,464633,422449,3,1,365
14,C:/Users/Sawan/Documents/dataset\modis\2014\mo...,dataset\modis\2014\modis_2014_India.csv,76416,15,2014-01-01,2014-12-31,"[Terra, Aqua]",MODIS,6.20,55985,56911,101,2,360
24,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2014\viirs-snpp_2014_India.csv,536158,15,2014-01-01,2014-12-31,[N],VIIRS,1.00,506719,458496,3,1,364
15,C:/Users/Sawan/Documents/dataset\modis\2015\mo...,dataset\modis\2015\modis_2015_India.csv,68433,15,2015-01-01,2015-12-31,"[Terra, Aqua]",MODIS,6.20,51856,52745,100,2,361
25,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2015\viirs-snpp_2015_India.csv,479234,15,2015-01-01,2015-12-31,[N],VIIRS,1.00,454207,414919,3,1,365
16,C:/Users/Sawan/Documents/dataset\modis\2016\mo...,dataset\modis\2016\modis_2016_India.csv,88809,15,2016-01-01,2016-12-31,"[Terra, Aqua]",MODIS,6.20,63971,64075,101,2,360
26,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2016\viirs-snpp_2016_India.csv,674483,15,2016-01-01,2016-12-31,[N],VIIRS,1.00,630925,553874,3,1,366
17,C:/Users/Sawan/Documents/dataset\modis\2017\mo...,dataset\modis\2017\modis_2017_India.csv,82545,15,2017-01-01,2017-12-31,"[Terra, Aqua]",MODIS,6.20,61610,62340,99,2,361
27,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2017\viirs-snpp_2017_India.csv,596995,15,2017-01-01,2017-12-31,[N],VIIRS,1.00,561077,499462,3,1,365
18,C:/Users/Sawan/Documents/dataset\modis\2018\mo...,dataset\modis\2018\modis_2018_India.csv,91110,15,2018-01-01,2018-12-31,"[Terra, Aqua]",MODIS,6.03,65663,66287,101,2,361
28,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2018\viirs-snpp_2018_India.csv,642984,15,2018-01-01,2018-12-31,[N],VIIRS,1.00,600863,532014,3,1,365
19,C:/Users/Sawan/Documents/dataset\modis\2019\mo...,dataset\modis\2019\modis_2019_India.csv,75502,15,2019-01-01,2019-12-31,"[Terra, Aqua]",MODIS,6.03,57227,57304,101,2,364
29,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2019\viirs-snpp_2019_India.csv,531728,15,2019-01-01,2019-12-31,[N],VIIRS,1.00,502812,450743,3,1,365
20,C:/Users/Sawan/Documents/dataset\modis\2020\mo...,dataset\modis\2020\modis_2020_India.csv,76021,15,2020-01-01,2020-12-31,"[Terra, Aqua]",MODIS,6.03,54606,56016,101,2,364
30,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2020\viirs-snpp_2020_India.csv,482825,15,2020-01-01,2020-12-31,[N],VIIRS,1.00,455808,411346,3,1,366
21,C:/Users/Sawan/Documents/dataset\modis\2021\mo...,dataset\modis\2021\modis_2021_India.csv,111267,15,2021-01-01,2021-12-31,"[Terra, Aqua]",MODIS,6.03,75290,78672,101,2,364
31,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2021\viirs-snpp_2021_India.csv,765760,15,2021-01-01,2021-12-31,[N],VIIRS,1.00,711120,626016,3,1,364

Total Rows: 7295870

In [34]:
fire_df

[      latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0      23.6805    86.0949       318.9   1.2    1.1  2000-11-01     0501
 1      22.7913    86.2102       326.4   1.2    1.1  2000-11-01     0501
 2      22.7885    86.2037       320.7   1.2    1.1  2000-11-01     0501
 3      22.7870    86.2150       319.7   1.2    1.1  2000-11-01     0501
 4      18.7651    79.9640       315.9   2.7    1.6  2000-11-01     0503
 ...        ...        ...         ...   ...    ...         ...      ...
 1402   18.3733    84.0124       321.3   1.2    1.1  2000-12-31     0526
 1403   17.0570    81.6077       317.3   1.0    1.0  2000-12-31     0527
 1404   17.1694    80.3962       314.5   1.0    1.0  2000-12-31     0527
 1405   16.6299    80.4980       311.3   1.0    1.0  2000-12-31     0527
 1406   26.8090    95.3769       301.5   1.5    1.2  2000-12-31     1622

      satellite instrument  confidence  version  bright_t31   frp daynight  \
 0        Terra      MODIS          67      6.2       303.3  12.1        D
 1        Terra      MODIS          54      6.2       299.4  19.8        D
 2        Terra      MODIS          65      6.2       299.1  15.0        D
 3        Terra      MODIS          66      6.2       298.5  13.8        D
 4        Terra      MODIS          18      6.2       298.3  28.8        D
 ...        ...        ...         ...      ...         ...   ...      ...
 1402     Terra      MODIS          73      6.2       300.9  15.1        D
 1403     Terra      MODIS          68      6.2       299.1   8.2        D
 1404     Terra      MODIS          59      6.2       297.4   7.1        D
 1405     Terra      MODIS          39      6.2       297.2   5.0        D
 1406     Terra      MODIS          42      6.2       282.1  13.2        N

       type
 0        2
 1        0
 2        0
 3        0
 4        0
 ...    ...
 1402     0
 1403     0
 1404     0
 1405     0
 1406     0

 [1407 rows x 15 columns],
        latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0       26.9708    95.6775       331.1   1.1    1.0  2001-01-01     0429
 1       26.9694    95.6878       331.1   1.1    1.0  2001-01-01     0429
 2       26.9601    95.6868       307.2   1.1    1.0  2001-01-01     0429
 3       26.9154    95.3308       352.2   1.1    1.0  2001-01-01     0429
 4       26.8176    95.3756       328.7   1.1    1.0  2001-01-01     0429
 ...         ...        ...         ...   ...    ...         ...      ...
 18714   17.1957    74.2174       319.8   1.1    1.0  2001-12-31     1718
 18715   17.2924    74.1222       310.3   1.1    1.0  2001-12-31     1718
 18716   18.6373    73.2075       302.3   1.2    1.1  2001-12-31     1718
 18717   21.4923    73.0496       305.4   1.1    1.0  2001-12-31     1719
 18718   21.5016    73.0479       307.9   1.1    1.0  2001-12-31     1719

       satellite instrument  confidence  version  bright_t31   frp daynight  \
 0         Terra      MODIS          87      6.2       288.2  33.2        D
 1         Terra      MODIS          87      6.2       289.3  33.3        D
 2         Terra      MODIS          65      6.2       287.3   8.9        D
 3         Terra      MODIS          97      6.2       290.4  76.7        D
 4         Terra      MODIS          86      6.2       289.0  30.0        D
 ...         ...        ...         ...      ...         ...   ...      ...
 18714     Terra      MODIS          99      6.2       289.4  21.6        N
 18715     Terra      MODIS          80      6.2       290.4  12.9        N
 18716     Terra      MODIS          48      6.2       290.4   6.1        N
 18717     Terra      MODIS          64      6.2       289.4   8.4        N
 18718     Terra      MODIS          73      6.2       289.9  10.1        N

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 18714     0
 18715     0
 18716     0
 18717     0
 18718     0

 [18719 rows x 15 columns],
        latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0       30.3180    79.5568       307.1   1.1    1.0  2002-01-01     0526
 1       31.7253    77.1147       304.3   1.4    1.2  2002-01-01     0526
 2       30.0876    79.8322       303.1   1.0    1.0  2002-01-01     0526
 3       31.7211    77.1063       304.2   1.4    1.2  2002-01-01     0526
 4       25.2167    82.3508       304.7   1.1    1.1  2002-01-01     0527
 ...         ...        ...         ...   ...    ...         ...      ...
 26746   19.4849    75.5168       315.3   3.4    1.7  2002-12-31     0855
 26747   19.4815    75.5090       313.7   3.4    1.7  2002-12-31     0855
 26748   21.0175    72.8294       313.7   2.2    1.4  2002-12-31     0855
 26749   21.0190    72.8434       312.4   2.2    1.4  2002-12-31     0855
 26750   17.9926    74.7328       300.6   3.3    1.7  2002-12-31     1645

       satellite instrument  confidence  version  bright_t31   frp daynight  \
 0         Terra      MODIS          51      6.2       285.5   9.0        D
 1         Terra      MODIS          52      6.2       287.3  10.7        D
 2         Terra      MODIS          12      6.2       292.7   7.1        D
 3         Terra      MODIS          53      6.2       286.2  10.6        D
 4         Terra      MODIS           0      6.2       294.7   6.1        D
 ...         ...        ...         ...      ...         ...   ...      ...
 26746      Aqua      MODIS          61      6.2       298.4  37.8        D
 26747      Aqua      MODIS          57      6.2       298.1  31.6        D
 26748      Aqua      MODIS          53      6.2       300.8  18.9        D
 26749      Aqua      MODIS          49      6.2       300.0  17.8        D
 26750     Terra      MODIS          31      6.2       285.6  34.5        N

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 26746     0
 26747     0
 26748     0
 26749     0
 26750     0

 [26751 rows x 15 columns],
        latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0       22.7907    86.2043       309.7   1.0    1.0  2003-01-01     0455
 1       21.7949    83.9021       312.1   1.2    1.1  2003-01-01     0456
 2       12.0587    79.0869       313.8   1.9    1.4  2003-01-01     0458
 3       12.7143    79.3960       314.2   1.9    1.3  2003-01-01     0458
 4       13.7463    79.8443       317.7   1.1    1.0  2003-01-01     0758
 ...         ...        ...         ...   ...    ...         ...      ...
 56086   30.8093    77.9025       305.7   2.0    1.4  2003-12-31     0827
 56087   31.2842    75.0930       309.0   1.3    1.1  2003-12-31     0827
 56088   22.3923    73.1222       310.2   1.5    1.2  2003-12-31     2034
 56089   19.1557    73.2359       300.5   1.4    1.2  2003-12-31     2035
 56090   17.9564    75.0792       309.2   1.1    1.0  2003-12-31     2036

       satellite instrument  confidence  version  bright_t31   frp daynight  \
 0         Terra      MODIS           0      6.2       293.3   7.5        D
 1         Terra      MODIS          61      6.2       298.4   7.6        D
 2         Terra      MODIS          61      6.2       297.9  13.0        D
 3         Terra      MODIS          60      6.2       298.4  11.8        D
 4          Aqua      MODIS          33      6.2       302.5   7.5        D
 ...         ...        ...         ...      ...         ...   ...      ...
 56086      Aqua      MODIS          42      6.2       290.5  20.4        D
 56087      Aqua      MODIS          51      6.2       288.3  13.2        D
 56088      Aqua      MODIS          79      6.2       286.6  23.2        N
 56089      Aqua      MODIS          29      6.2       288.9   8.1        N
 56090      Aqua      MODIS          77      6.2       285.2  12.6        N

        type
 0         2
 1         0
 2         0
 3         0
 4         0
 ...     ...
 56086     0
 56087     0
 56088     0
 56089     0
 56090     0

 [56091 rows x 15 columns],
        latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0       27.3164    95.2654       302.9   1.0    1.0  2004-01-01     0423
 1       28.7178    94.3186       312.3   1.1    1.0  2004-01-01     0423
 2       28.9738    95.7857       307.5   1.0    1.0  2004-01-01     0423
 3       27.4529    95.0846       306.9   1.0    1.0  2004-01-01     0423
 4       28.8763    96.0175       351.9   1.0    1.0  2004-01-01     0423
 ...         ...        ...         ...   ...    ...         ...      ...
 64720   17.7558    77.6242       319.7   2.1    1.4  2004-12-31     0836
 64721   17.7582    77.6165       325.5   2.1    1.4  2004-12-31     0836
 64722   17.7536    77.6050       323.3   2.1    1.4  2004-12-31     0836
 64723   23.2180    70.6233       322.3   1.0    1.0  2004-12-31     0838
 64724   21.3623    71.8228       300.0   1.2    1.1  2004-12-31     2047

       satellite instrument  confidence  version  bright_t31   frp daynight  \
 0         Terra      MODIS          54      6.2       292.5   3.5        D
 1         Terra      MODIS          72      6.2       288.0  14.1        D
 2         Terra      MODIS          65      6.2       283.2  10.7        D
 3         Terra      MODIS          23      6.2       287.5   6.0        D
 4         Terra      MODIS          97      6.2       287.7  70.2        D
 ...         ...        ...         ...      ...         ...   ...      ...
 64720      Aqua      MODIS          50      6.2       305.6  16.2        D
 64721      Aqua      MODIS          72      6.2       305.4  34.8        D
 64722      Aqua      MODIS          67      6.2       305.5  27.4        D
 64723      Aqua      MODIS          68      6.2       304.4  13.2        D
 64724      Aqua      MODIS           3      6.2       285.8   8.1        N

        type
 0         0
 1         0
 2         0
 3         2
 4         0
 ...     ...
 64720     0
 64721     0
 64722     0
 64723     0
 64724     0

 [64725 rows x 15 columns],
        latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0       27.5703    94.4392       305.2   1.0    1.0  2005-01-01     0434
 1       26.6397    93.2284       307.1   1.0    1.0  2005-01-01     0434
 2       27.4477    95.0844       314.3   1.1    1.0  2005-01-01     0434
 3       27.4460    95.0953       303.2   1.1    1.0  2005-01-01     0434
 4       26.5882    93.0187       306.3   1.0    1.0  2005-01-01     0434
 ...         ...        ...         ...   ...    ...         ...      ...
 63480   16.4203    74.5545       300.2   1.2    1.1  2005-12-31     1732
 63481   20.9253    70.4811       302.8   1.0    1.0  2005-12-31     1733
 63482   21.7907    72.6491       303.8   1.1    1.1  2005-12-31     1733
 63483   24.1501    82.7577       305.0   1.0    1.0  2005-12-31     2015
 63484   21.2021    81.4169       304.5   1.0    1.0  2005-12-31     2015

       satellite instrument  confidence  version  bright_t31   frp daynight  \
 0         Terra      MODIS          44      6.2       293.2   5.4        D
 1         Terra      MODIS          49      6.2       296.7   6.5        D
 2         Terra      MODIS          75      6.2       292.4  12.9        D
 3         Terra      MODIS          55      6.2       291.9   4.1        D
 4         Terra      MODIS          47      6.2       295.9   5.3        D
 ...         ...        ...         ...      ...         ...   ...      ...
 63480     Terra      MODIS          20      6.2       289.4   6.5        N
 63481     Terra      MODIS          51      6.2       284.7   7.4        N
 63482     Terra      MODIS          57      6.2       287.1   9.3        N
 63483      Aqua      MODIS          63      6.2       286.3   8.9        N
 63484      Aqua      MODIS          60      6.2       286.4   8.3        N

        type
 0         0
 1         0
 2         2
 3         2
 4         0
 ...     ...
 63480     0
 63481     0
 63482     0
 63483     2
 63484     2

 [63485 rows x 15 columns],
        latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0       28.2411    96.9910       338.8   1.3    1.2  2006-01-01     0402
 1       28.2398    97.0024       311.2   1.3    1.1  2006-01-01     0402
 2       28.1899    97.0025       303.4   1.3    1.1  2006-01-01     0402
 3       26.7851    95.4348       335.1   1.6    1.2  2006-01-01     0403
 4       26.7741    95.4316       345.0   1.6    1.2  2006-01-01     0403
 ...         ...        ...         ...   ...    ...         ...      ...
 65975   17.8940    76.4995       309.1   1.2    1.1  2006-12-31     1702
 65976   16.6113    75.1546       301.0   1.5    1.2  2006-12-31     1702
 65977   22.3426    82.4999       304.5   1.5    1.2  2006-12-31     1703
 65978   23.0176    79.3436       301.3   1.1    1.0  2006-12-31     1704
 65979   21.2030    81.4239       300.3   3.0    1.6  2006-12-31     1948

       satellite instrument  confidence  version  bright_t31    frp daynight  \
 0         Terra      MODIS          91      6.2       288.5   67.6        D
 1         Terra      MODIS          65      6.2       287.1   18.2        D
 2         Terra      MODIS          53      6.2       286.2   11.0        D
 3         Terra      MODIS          89      6.2       294.4   70.4        D
 4         Terra      MODIS          94      6.2       292.4  104.2        D
 ...         ...        ...         ...      ...         ...    ...      ...
 65975     Terra      MODIS          77      6.2       288.4   13.3        N
 65976     Terra      MODIS          37      6.2       288.2    9.8        N
 65977     Terra      MODIS          60      6.2       288.9   14.1        N
 65978     Terra      MODIS          40      6.2       285.3    7.2        N
 65979      Aqua      MODIS          24      6.2       287.7   27.0        N

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 65975     0
 65976     0
 65977     2
 65978     0
 65979     2

 [65980 rows x 15 columns],
        latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0       31.0826    78.2367       302.4   1.9    1.3  2007-01-01     0510
 1       29.2593    79.0382       308.0   1.6    1.2  2007-01-01     0511
 2       25.1046    80.1547       307.1   1.2    1.1  2007-01-01     0512
 3       24.5620    78.1292       311.3   1.6    1.2  2007-01-01     0512
 4       24.5618    78.1223       308.2   1.6    1.2  2007-01-01     0512
 ...         ...        ...         ...   ...    ...         ...      ...
 75315   22.3296    69.7341       302.0   3.0    1.7  2007-12-31     1811
 75316   27.8604    95.4357       318.3   1.3    1.1  2007-12-31     1914
 75317   27.8620    95.4223       310.2   1.3    1.1  2007-12-31     1914
 75318   22.3364    69.7421       303.5   1.3    1.1  2007-12-31     2055
 75319   16.5604    74.4877       312.4   1.2    1.1  2007-12-31     2056

       satellite instrument  confidence  version  bright_t31   frp daynight  \
 0         Terra      MODIS          38      6.2       292.1  19.8        D
 1         Terra      MODIS          66      6.2       289.0  16.3        D
 2         Terra      MODIS          51      6.2       295.8   4.7        D
 3         Terra      MODIS          63      6.2       297.2  11.4        D
 4         Terra      MODIS          56      6.2       298.1   8.6        D
 ...         ...        ...         ...      ...         ...   ...      ...
 75315     Terra      MODIS          46      6.2       283.3  39.3        N
 75316      Aqua      MODIS          97      6.2       285.3  28.4        N
 75317      Aqua      MODIS          79      6.2       285.0  18.2        N
 75318      Aqua      MODIS          56      6.2       282.6  12.9        N
 75319      Aqua      MODIS          85      6.2       288.6  16.5        N

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 75315     0
 75316     0
 75317     0
 75318     0
 75319     0

 [75320 rows x 15 columns],
        latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0       27.8739    95.4367       324.4   1.3    1.1  2008-01-01     0440
 1       27.9284    95.9297       308.1   1.4    1.2  2008-01-01     0440
 2       27.9339    95.9251       310.7   1.4    1.2  2008-01-01     0440
 3       26.2184    91.7610       309.9   1.0    1.0  2008-01-01     0441
 4       25.8978    92.1036       303.1   1.0    1.0  2008-01-01     0441
 ...         ...        ...         ...   ...    ...         ...      ...
 70908   24.2077    82.7195       303.1   1.0    1.0  2008-12-31     1646
 70909   23.7680    86.3923       301.5   1.4    1.2  2008-12-31     1646
 70910   22.3302    82.6595       301.7   1.0    1.0  2008-12-31     1646
 70911   24.1482    82.7559       302.1   1.0    1.0  2008-12-31     1646
 70912   23.6721    85.0006       300.5   1.2    1.1  2008-12-31     1646

       satellite instrument  confidence  version  bright_t31   frp daynight  \
 0         Terra      MODIS          69      6.2       295.6  24.9        D
 1         Terra      MODIS          51      6.2       296.2   8.6        D
 2         Terra      MODIS          69      6.2       296.1  11.1        D
 3         Terra      MODIS           0      6.2       299.7   6.9        D
 4         Terra      MODIS          53      6.2       290.8   4.8        D
 ...         ...        ...         ...      ...         ...   ...      ...
 70908     Terra      MODIS          53      6.2       288.7   7.5        N
 70909     Terra      MODIS          41      6.2       289.1   9.9        N
 70910     Terra      MODIS          43      6.2       288.7   6.1        N
 70911     Terra      MODIS          47      6.2       287.2   6.9        N
 70912     Terra      MODIS          29      6.2       284.9   8.9        N

        type
 0         0
 1         0
 2         0
 3         0
 4         0
 ...     ...
 70908     2
 70909     2
 70910     0
 70911     2
 70912     0

 [70913 rows x 15 columns],
        latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0       30.0366    80.5721       306.9   2.7    1.6  2009-01-01     0453
 1       23.7890    86.2427       313.3   1.0    1.0  2009-01-01     0455
 2       22.7911    86.2063       317.1   1.0    1.0  2009-01-01     0455
 3       23.6711    85.0084       310.2   1.1    1.1  2009-01-01     0455
 4       23.6818    86.0854       313.3   1.0    1.0  2009-01-01     0455
 ...         ...        ...         ...   ...    ...         ...      ...
 90231   23.7943    86.2370       301.5   1.4    1.2  2009-12-31     1615
 90232   22.7922    86.2053       303.5   1.4    1.2  2009-12-31     1615
 90233   23.7705    86.3948       300.9   1.3    1.1  2009-12-31     1615
 90234   17.9524    80.8091       301.7   1.4    1.2  2009-12-31     2041
 90235   15.1784    76.6617       301.5   1.0    1.0  2009-12-31     2042

       satellite instrument  confidence  version  bright_t31   frp daynight  \
 0         Terra      MODIS          60      6.2       289.6  38.5        D
 1         Terra      MODIS          68      6.2       299.4   7.8        D
 2         Terra      MODIS           0      6.2       297.1  11.4        D
 3         Terra      MODIS          62      6.2       297.2   7.2        D
 4         Terra      MODIS          59      6.2       297.8   7.8        D
 ...         ...        ...         ...      ...         ...   ...      ...
 90231     Terra      MODIS          42      6.2       286.1  10.9        N
 90232     Terra      MODIS          56      6.2       288.9  12.1        N
 90233     Terra      MODIS          34      6.2       288.0   9.3        N
 90234      Aqua      MODIS          44      6.2       291.7   8.4        N
 90235      Aqua      MODIS          42      6.2       291.3   4.1        N

        type
 0         0
 1         2
 2         2
 3         0
 4         2
 ...     ...
 90231     2
 90232     2
 90233     2
 90234     2
 90235     0

 [90236 rows x 15 columns],
        latitude  longitude  brightness  scan  track    acq_date acq_time  \

In [35]:
india_fire_df = pd.concat(fire_df)
india_fire_df.shape

(7295870, 17)

In [36]:
india_fire_df.sample(10)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,bright_ti4,bright_ti5
142453,18.430101,81.080238,NaN,0.39,0.36,2012-03-12,0751,N,VIIRS,0,1.0,NaN,4.42,D,0,337.01,308.76
325804,13.069384,79.827705,NaN,0.40,0.60,2012-04-21,1933,N,VIIRS,50,1.0,NaN,1.15,N,0,305.75,293.85
255927,24.445066,94.124550,NaN,0.66,0.73,2014-04-14,0752,N,VIIRS,50,1.0,NaN,57.32,D,0,352.60,307.95
178579,21.207603,83.021049,NaN,0.40,0.37,2017-03-27,0733,N,VIIRS,50,1.0,NaN,15.33,D,0,348.87,319.05
239289,9.536244,77.049400,NaN,0.42,0.38,2015-04-16,0807,N,VIIRS,50,1.0,NaN,14.42,D,0,343.96,297.03
298595,19.802494,81.154510,NaN,0.39,0.36,2016-04-08,0753,N,VIIRS,0,1.0,NaN,2.79,D,0,332.87,307.51
540636,20.407757,75.209564,NaN,0.43,0.38,2021-04-26,2042,N,VIIRS,50,1.0,NaN,3.44,N,0,333.54,298.99
215132,24.119890,93.306702,NaN,0.51,0.66,2012-03-23,0606,N,VIIRS,100,1.0,NaN,52.96,D,0,367.00,298.83
28539,24.842500,87.445000,323.5,1.20,1.10,2014-04-03,0506,Terra,MODIS,57,6.2,309.3,7.30,D,0,NaN,NaN
41658,30.612300,75.916800,315.4,1.50,1.20,2005-10-07,0749,Aqua,MODIS,61,6.2,302.2,10.00,D,0,NaN,NaN

In [38]:
india_fire_df = india_fire_df.sort_values(by=['acq_date', 'acq_time'])

In [39]:
india_fire_df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,bright_ti4,bright_ti5
0,23.680500,86.094900,318.9,1.20,1.10,2000-11-01,0501,Terra,MODIS,67,6.2,303.3,12.10,D,2,NaN,NaN
1,22.791300,86.210200,326.4,1.20,1.10,2000-11-01,0501,Terra,MODIS,54,6.2,299.4,19.80,D,0,NaN,NaN
2,22.788500,86.203700,320.7,1.20,1.10,2000-11-01,0501,Terra,MODIS,65,6.2,299.1,15.00,D,0,NaN,NaN
3,22.787000,86.215000,319.7,1.20,1.10,2000-11-01,0501,Terra,MODIS,66,6.2,298.5,13.80,D,0,NaN,NaN
4,18.765100,79.964000,315.9,2.70,1.60,2000-11-01,0503,Terra,MODIS,18,6.2,298.3,28.80,D,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
765755,22.938877,69.697998,NaN,0.53,0.42,2021-12-31,2118,N,VIIRS,50,1.0,NaN,0.76,N,2,300.85,286.16
765756,21.108959,72.634842,NaN,0.56,0.52,2021-12-31,2118,N,VIIRS,50,1.0,NaN,1.15,N,3,304.64,290.36
765757,18.688864,73.040932,NaN,0.33,0.56,2021-12-31,2118,N,VIIRS,50,1.0,NaN,1.18,N,2,302.86,291.75
765758,15.176281,76.787415,NaN,0.68,0.74,2021-12-31,2118,N,VIIRS,50,1.0,NaN,1.19,N,2,298.04,286.08
765759,19.248699,76.168533,NaN,0.51,0.66,2021-12-31,2118,N,VIIRS,50,1.0,NaN,1.33,N,0,310.39,283.60

In [40]:
india_fire_df['confidence'].nunique()

101

In [41]:
india_fire_df['confidence'].unique()

array([ 67,  54,  65,  66,  18,  61,  30,  48,  51, 100,  60,  63,  52,
        89,  84,  64,  56,  82,  62,  57,  59,  50,  55,  38,   0,  36,
        25,  40,  71,  70,  79,  44,  77,  24,  43,  47,  49,  72,  34,
        87,  73,  68,  53,  75,  81,  45,  85,  35,  11,  32,  98,  91,
        76,  58,  37,  46,  74,  93,  29,  23,  69,  28,  39,  27,  42,
        33,  97,  20,  26,  41,  78,  88,  90,  31,  15,  99,  83,  21,
        96,  94,  14,  80,  19,  86,  22,  92,   5,   9,  16,  95,   8,
        10,  17,  13,  12,   7,   2,   6,   1,   4,   3], dtype=int64)

# Brightness #
- brightness: Channel 21/22 brightness temperature of the fire pixel measured in Kelvin.

In [42]:
india_fire_df['brightness'].describe()

count    1.517093e+06
mean     3.247795e+02
std      1.530594e+01
min      3.000000e+02
25%      3.152000e+02
50%      3.227000e+02
75%      3.316000e+02
max      5.062000e+02
Name: brightness, dtype: float64

## Satellite ##

In [43]:
india_fire_df['satellite'].unique()

array(['Terra', 'Aqua', 'N'], dtype=object)

In [44]:
india_fire_df['instrument'].unique()

array(['MODIS', 'VIIRS'], dtype=object)

## bright_t31 ##
- Channel 31 brightness temperature of the fire pixel measured in Kelvin.

In [45]:
india_fire_df['bright_t31'].describe()

count    1.517093e+06
mean     3.034232e+02
std      8.391447e+00
min      2.660000e+02
25%      2.982000e+02
50%      3.025000e+02
75%      3.089000e+02
max      4.001000e+02
Name: bright_t31, dtype: float64

In [46]:
india_fire_df['bright_t31'].unique()

array([303.3, 299.4, 299.1, 298.5, 298.3, 289.7, 290. , 294.9, 300.5,
       293.2, 291.2, 292.4, 292.1, 292.5, 292.2, 291.9, 292.6, 293.9,
       294.2, 290.9, 298. , 301.1, 302.5, 301.5, 298.4, 300. , 303.4,
       302.4, 300.9, 301. , 299.3, 300.3, 302. , 303.5, 305.9, 306.7,
       306.3, 303.9, 304.3, 305.7, 301.7, 302.6, 304.2, 304.4, 288.8,
       288.9, 298.1, 283.7, 301.4, 302.8, 292.8, 292.3, 291.4, 300.2,
       294.7, 305.4, 301.9, 304.8, 305.3, 302.2, 303.2, 305.8, 298.7,
       298.2, 291.8, 303. , 304. , 308.6, 285.1, 286.9, 291.7, 289.2,
       291.5, 295. , 295.7, 297. , 305.1, 302.7, 297.9, 297.7, 298.6,
       306.8, 287.3, 305. , 304.9, 303.8, 306.4, 305.6, 309.4, 309.6,
       290.6, 291.6, 295.1, 285.3, 304.7, 306.6, 304.1, 299.6, 300.1,
       300.4, 299.8, 289.3, 293.5, 287.5, 286.1, 282.9, 290.2, 286.7,
       285.9, 301.3, 302.1, 300.6, 307.3, 306.9, 293. , 299.2, 289.4,
       295.6, 299.7, 305.5, 308.1, 308.5, 307.9, 304.6, 289.5, 298.8,
       294.1, 287.6, 294.6, 306.1, 308.8, 307.1, 302.3, 292.9, 300.8,
       297.6, 298.9, 308.7, 307. , 304.5, 290.4, 287.8, 297.1, 295.2,
       296.9, 310. , 289. , 288.5, 285. , 284.4, 283.8, 296.4, 296.8,
       306. , 306.5, 296.7, 308.9, 307.8, 291.1, 294.8, 301.6, 289.6,
       308.4, 297.4, 290.3, 289.9, 297.5, 295.9, 296.1, 296.3, 297.3,
       296.6, 301.8, 290.5, 288.6, 295.8, 297.8, 299.9, 303.1, 302.9,
       296. , 291. , 296.5, 305.2, 293.4, 293.3, 285.6, 295.4, 297.2,
       299. , 294.3, 294.5, 294.4, 296.2, 303.7, 287.1, 290.7, 290.1,
       289.8, 287.7, 286.3, 286.4, 295.5, 293.8, 295.3, 307.5, 286.5,
       288.4, 293.6, 293.7, 307.4, 309.8, 301.2, 303.6, 299.5, 278.8,
       288.3, 287.2, 291.3, 300.7, 279.8, 307.7, 310.5, 307.2, 286.2,
       279.1, 293.1, 294. , 292. , 284.7, 284.5, 286.6, 292.7, 285.7,
       284.1, 281.7, 285.2, 308.3, 287.9, 282.8, 310.8, 285.8, 286. ,
       308. , 309.2, 306.2, 281.2, 282.2, 280. , 280.8, 309.3, 288.2,
       288.7, 283.6, 288. , 284.6, 283. , 283.1, 290.8, 283.5, 319.5,
       284.3, 282.4, 279.7, 281.6, 288.1, 282.1, 281.8, 289.1, 283.3,
       282.6, 286.8, 278.3, 275.4, 278.7, 283.9, 284. , 277.5, 281.3,
       281.9, 284.2, 287. , 284.9, 278.1, 285.4, 281.4, 287.4, 313.9,
       310.4, 277.6, 308.2, 307.6, 274.4, 309.5, 283.2, 276.6, 282.3,
       281.5, 312.2, 310.2, 309.7, 278.4, 309. , 311.3, 310.3, 313. ,
       311.2, 312.1, 310.1, 314.2, 315.3, 313.1, 311. , 311.5, 272.4,
       278.6, 277.8, 309.9, 313.3, 312.4, 310.6, 309.1, 311.7, 315.7,
       311.6, 311.1, 277.9, 314.5, 316.2, 312.5, 285.5, 277.7, 312.8,
       310.7, 312. , 311.8, 318.1, 313.6, 312.9, 313.2, 312.3, 312.6,
       323.6, 283.4, 278. , 280.3, 284.8, 315. , 311.9, 314. , 312.7,
       310.9, 314.9, 313.4, 315.5, 314.3, 313.8, 316.4, 313.5, 315.6,
       317. , 316. , 316.5, 315.8, 313.7, 314.1, 311.4, 316.7, 316.3,
       318.4, 282.5, 314.4, 315.2, 316.1, 314.6, 317.2, 314.7, 314.8,
       317.7, 274.7, 275.5, 273.3, 267.8, 271.1, 279. , 271.7, 275.8,
       280.2, 274.5, 280.5, 276.4, 315.9, 319.6, 321.8, 325.3, 319.1,
       362.2, 356.5, 326.1, 320.5, 324.3, 321.6, 318.5, 317.9, 318.2,
       317.6, 316.9, 281.1, 315.1, 317.8, 317.3, 317.4, 317.1, 315.4,
       316.8, 318.3, 323. , 279.4, 277.4, 271.5, 272.9, 274.8, 274. ,
       319.4, 318.7, 318.9, 316.6, 318.6, 318. , 320.2, 318.8, 321.1,
       320.1, 319.7, 321.3, 319. , 319.9, 319.2, 317.5, 320. , 282.7,
       280.6, 320.7, 321.2, 320.6, 319.8, 319.3, 346.7, 321.9, 322.6,
       326.2, 323.5, 321.4, 322.3, 320.8, 322.9, 322.1, 321. , 321.5,
       323.1, 324.2, 323.7, 321.7, 320.9, 322. , 323.9, 324.1, 320.3,
       280.7, 276.9, 320.4, 322.5, 322.2, 278.9, 279.9, 280.4, 267. ,
       322.4, 324.4, 324.6, 325.9, 325.2, 328. , 328.9, 326.4, 324.5,
       324.7, 323.2, 322.8, 275.3, 325.1, 325.4, 322.7, 323.3, 323.8,
       323.4, 324. , 278.5, 277.2, 279.5, 275.6, 279.3, 280.9, 279.6,
       276.1, 277. , 280.1, 272.5, 274.1, 272.7, 272.3, 269.4, 274.6,
       268.1, 270.4, 275.2, 325.8, 324.9, 325. , 282. , 329.2, 270.2,
       272. , 326.3, 327.4, 326.6, 327.3, 325.7, 330.3, 326.7, 326.8,
       327. , 273.8, 273.9, 278.2, 273. , 271.4, 271.2, 281. , 277.3,
       276.2, 271.8, 266.4, 277.1, 273.2, 279.2, 273.6, 270.6, 275.7,
       276.8, 340.8, 325.5, 327.9, 333.5, 400.1, 338.7, 330.5, 328.2,
       330.4, 329.5, 329.9, 327.1, 349.8, 273.5, 332.1, 274.3, 271.9,
       271.3, 275. , 274.9, 276. , 269.5, 324.8, 328.1, 270.7, 274.2,
       341.7, 339.7, 276.3, 330.8, 335.2, 327.7, 336.5, 335.7, 334.6,
       336.6, 335.6, 332.2, 329.6, 333.4, 326. , 340.4, 329.3, 331.7,
       276.5, 335.5, 269.2, 272.2, 269.1, 336.3, 271.6, 269.7, 327.8,
       327.5, 325.6, 327.2, 326.9, 328.8, 272.6, 334.7, 328.5, 268.8,
       328.4, 275.1, 270.5, 270.9, 276.7, 329.4, 332.3, 339.2, 335.1,
       335.8, 340.2, 340.7, 338.1, 337. , 342.1, 342. , 340.1, 338. ,
       334. , 329.1, 330.6, 331.2, 272.1, 331.3, 268.9, 269.6, 268.3,
       333.1, 268.4, 270.8, 336.2, 328.3, 327.6, 338.8, 337.8, 342.6,
       330. , 326.5, 330.2, 342.3, 334.1, 338.9, 336.4, 268.5, 268.6,
       332.4, 328.7, 272.8, 329.8, 275.9, 339.5, 330.7, 332. , 330.1,
       332.8, 270.1, 331.8, 273.7, 341.3, 268.2, 267.6, 273.4, 333. ,
       343. , 336.9, 332.9, 271. , 329.7, 341.6, 334.9, 273.1, 334.4,
       339.1, 328.6, 331.6, 331.5, 336.7, 334.5, 270.3, 268.7, 266. ,
       337.7, 340.6, 335.9, 333.8, 337.4, 333.9, 340.3, 338.2, 337.9,
       331.9, 338.3, 342.9, 270. , 339.8, 333.2, 269. , 333.3, 338.5,
       331. , 341.1, 269.9, 266.7, 267.4, 269.3, 267.7, 267.5, 269.8,
       332.5, 329. , 337.2, 331.1, 330.9, 332.7, 332.6, 334.8, 266.1,
       267.2, 331.4, 267.1, 335. , 337.1, 334.3, 337.3, 339.9, 334.2,
       341.9, 336.1, 268. ,   nan, 333.7, 340. , 267.3, 337.5, 266.9,
       266.8, 345.7, 267.9, 349.6, 336.8, 339.3, 339.4, 336. , 343.2,
       341.2, 335.4, 333.6, 335.3, 340.9, 341.4])

## frp ##
- Fire Radiative Power depicts the pixel-integrated fire radiative power in MW (megawatts).

In [47]:
india_fire_df['frp'].describe()

count    7.295870e+06
mean     1.161839e+01
std      4.343245e+01
min      0.000000e+00
25%      2.400000e+00
50%      4.910000e+00
75%      1.000000e+01
max      1.121200e+04
Name: frp, dtype: float64

## type ##
- Inferred hot spot type
  - 0 = presumed vegetation fire
  - 1 = active volcano
  - 2 = other static land source
  - 3 = offshore

In [48]:
india_fire_df['type'].unique()

array([2, 0, 3, 1], dtype=int64)

## Confidence ##
- This value is based on a collection of intermediate algorithm quantities used in the detection process. 
- It is intended to help users gauge the quality of individual hotspot/fire pixels. 
- Confidence estimates range between 0 and 100% and are assigned one of the three fire classes
  - low-confidence fire
  - nominal-confidence fire
  - high-confidence fire).

In [49]:
india_fire_df['confidence'].unique()

array([ 67,  54,  65,  66,  18,  61,  30,  48,  51, 100,  60,  63,  52,
        89,  84,  64,  56,  82,  62,  57,  59,  50,  55,  38,   0,  36,
        25,  40,  71,  70,  79,  44,  77,  24,  43,  47,  49,  72,  34,
        87,  73,  68,  53,  75,  81,  45,  85,  35,  11,  32,  98,  91,
        76,  58,  37,  46,  74,  93,  29,  23,  69,  28,  39,  27,  42,
        33,  97,  20,  26,  41,  78,  88,  90,  31,  15,  99,  83,  21,
        96,  94,  14,  80,  19,  86,  22,  92,   5,   9,  16,  95,   8,
        10,  17,  13,  12,   7,   2,   6,   1,   4,   3], dtype=int64)

In [50]:
india_fire_df.columns

Index(['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date',
       'acq_time', 'satellite', 'instrument', 'confidence', 'version',
       'bright_t31', 'frp', 'daynight', 'type', 'bright_ti4', 'bright_ti5'],
      dtype='object')

## Extracting few main feautures from the dataset ##

In [51]:
daily_fires_df = india_fire_df.groupby(
            ['latitude', 'longitude', 'acq_date', 'satellite', 'instrument', 'frp', 'type', 'bright_t31']).confidence.max().reset_index()

In [52]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence
0,6.7586,93.8252,2008-02-17,Aqua,MODIS,17.3,3,291.4,100
1,6.7676,93.8266,2008-02-17,Aqua,MODIS,0.0,0,291.0,90
2,6.8233,93.8447,2005-03-05,Aqua,MODIS,21.6,0,296.6,62
3,6.8316,93.8478,2005-03-05,Terra,MODIS,75.9,0,299.3,76
4,6.8344,93.8429,2005-03-05,Aqua,MODIS,17.0,0,296.7,53
...,...,...,...,...,...,...,...,...,...
1517088,34.7680,74.3017,2016-10-29,Aqua,MODIS,24.8,0,293.5,61
1517089,34.7697,74.3222,2016-10-29,Aqua,MODIS,49.7,0,294.9,79
1517090,34.7753,77.5226,2002-06-04,Terra,MODIS,11.5,0,296.6,0
1517091,34.8954,76.8219,2019-10-02,Terra,MODIS,5.6,0,285.2,29
1517092,34.9015,77.9959,2012-09-12,Terra,MODIS,4.4,0,283.4,0

In [53]:
daily_fires_df = daily_fires_df[daily_fires_df.confidence >= 50]

In [54]:
daily_fires_df['confidence'].unique()

array([100,  90,  62,  76,  53,  63,  58,  61,  52,  65,  51,  72,  60,
        71,  86,  57,  73,  70,  69,  66,  55,  81,  84,  75,  68,  67,
        79,  59,  74,  54,  77,  87,  50,  78,  83,  56,  94,  80,  64,
        95,  82,  89,  85,  88,  93,  92,  96,  97,  98,  91,  99],
      dtype=int64)

In [55]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence
0,6.7586,93.8252,2008-02-17,Aqua,MODIS,17.3,3,291.4,100
1,6.7676,93.8266,2008-02-17,Aqua,MODIS,0.0,0,291.0,90
2,6.8233,93.8447,2005-03-05,Aqua,MODIS,21.6,0,296.6,62
3,6.8316,93.8478,2005-03-05,Terra,MODIS,75.9,0,299.3,76
4,6.8344,93.8429,2005-03-05,Aqua,MODIS,17.0,0,296.7,53
...,...,...,...,...,...,...,...,...,...
1517084,34.7623,74.4167,2011-12-02,Aqua,MODIS,14.3,0,288.5,61
1517086,34.7642,74.3970,2016-11-09,Aqua,MODIS,17.7,0,274.6,76
1517087,34.7655,74.4015,2016-11-07,Aqua,MODIS,25.1,0,292.0,75
1517088,34.7680,74.3017,2016-10-29,Aqua,MODIS,24.8,0,293.5,61
1517089,34.7697,74.3222,2016-10-29,Aqua,MODIS,49.7,0,294.9,79

In [56]:
daily_fires_df['acq_date'].min()

'2000-11-01'

In [57]:
daily_fires_df['acq_date'].max()

'2021-12-31'

In [58]:
daily_fires_df.describe()

,latitude,longitude,frp,type,bright_t31,confidence
count,1.234067e+06,1.234067e+06,1.234067e+06,1.234067e+06,1.234067e+06,1.234067e+06
mean,2.493547e+01,8.181922e+01,3.503458e+01,6.211818e-02,3.039719e+02,7.108912e+01
std,4.959032e+00,7.200739e+00,9.726793e+01,3.476643e-01,8.338147e+00,1.263173e+01
min,6.758600e+00,6.852740e+01,0.000000e+00,0.000000e+00,2.667000e+02,5.000000e+01
25%,2.199470e+01,7.573840e+01,1.000000e+01,0.000000e+00,2.986000e+02,6.100000e+01
50%,2.512140e+01,7.924840e+01,1.580000e+01,0.000000e+00,3.028000e+02,7.000000e+01
75%,2.993360e+01,8.833485e+01,2.920000e+01,0.000000e+00,3.095000e+02,7.900000e+01
max,3.476970e+01,9.733590e+01,1.121200e+04,3.000000e+00,4.001000e+02,1.000000e+02

In [59]:
daily_fires_df['acq_date'] = pd.to_datetime(daily_fires_df['acq_date'])

C:\Users\Sawan\AppData\Local\Temp\ipykernel_17800\1911553507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daily_fires_df['acq_date'] = pd.to_datetime(daily_fires_df['acq_date'])

In [60]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence
0,6.7586,93.8252,2008-02-17,Aqua,MODIS,17.3,3,291.4,100
1,6.7676,93.8266,2008-02-17,Aqua,MODIS,0.0,0,291.0,90
2,6.8233,93.8447,2005-03-05,Aqua,MODIS,21.6,0,296.6,62
3,6.8316,93.8478,2005-03-05,Terra,MODIS,75.9,0,299.3,76
4,6.8344,93.8429,2005-03-05,Aqua,MODIS,17.0,0,296.7,53
...,...,...,...,...,...,...,...,...,...
1517084,34.7623,74.4167,2011-12-02,Aqua,MODIS,14.3,0,288.5,61
1517086,34.7642,74.3970,2016-11-09,Aqua,MODIS,17.7,0,274.6,76
1517087,34.7655,74.4015,2016-11-07,Aqua,MODIS,25.1,0,292.0,75
1517088,34.7680,74.3017,2016-10-29,Aqua,MODIS,24.8,0,293.5,61
1517089,34.7697,74.3222,2016-10-29,Aqua,MODIS,49.7,0,294.9,79

In [61]:
daily_fires_df['year'] = daily_fires_df.acq_date.dt.year

C:\Users\Sawan\AppData\Local\Temp\ipykernel_17800\2902059493.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daily_fires_df['year'] = daily_fires_df.acq_date.dt.year

In [62]:
daily_fires_df['month'] = daily_fires_df.acq_date.dt.month

C:\Users\Sawan\AppData\Local\Temp\ipykernel_17800\1262889700.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daily_fires_df['month'] = daily_fires_df.acq_date.dt.month

In [63]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence,year,month
0,6.7586,93.8252,2008-02-17,Aqua,MODIS,17.3,3,291.4,100,2008,2
1,6.7676,93.8266,2008-02-17,Aqua,MODIS,0.0,0,291.0,90,2008,2
2,6.8233,93.8447,2005-03-05,Aqua,MODIS,21.6,0,296.6,62,2005,3
3,6.8316,93.8478,2005-03-05,Terra,MODIS,75.9,0,299.3,76,2005,3
4,6.8344,93.8429,2005-03-05,Aqua,MODIS,17.0,0,296.7,53,2005,3
...,...,...,...,...,...,...,...,...,...,...,...
1517084,34.7623,74.4167,2011-12-02,Aqua,MODIS,14.3,0,288.5,61,2011,12
1517086,34.7642,74.3970,2016-11-09,Aqua,MODIS,17.7,0,274.6,76,2016,11
1517087,34.7655,74.4015,2016-11-07,Aqua,MODIS,25.1,0,292.0,75,2016,11
1517088,34.7680,74.3017,2016-10-29,Aqua,MODIS,24.8,0,293.5,61,2016,10
1517089,34.7697,74.3222,2016-10-29,Aqua,MODIS,49.7,0,294.9,79,2016,10

In [64]:
daily_fires_df['acq_date'].min()

Timestamp('2000-11-01 00:00:00')

In [65]:
daily_fires_df['acq_date'].max()

Timestamp('2021-12-31 00:00:00')

In [66]:
daily_fires_df.to_csv('india_daily_fire_2000_2020.csv', index=False)
#ca_daily_fire.to_csv('ca_daily_fire_2012_2020.csv.gz', index=False, compression='gzip')

In [67]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 8E69-9D46

 Directory of C:\Users\Sawan\Documents\dataset

14-03-2023  11:47    <DIR>          .
14-03-2023  11:46    <DIR>          ..
14-03-2023  11:47        76,762,814 india_daily_fire_2000_2020.csv
13-03-2023  21:08    <DIR>          modis
14-03-2023  11:35         2,855,490 nepal_daily_fire_2000_2020.csv
13-03-2023  21:20    <DIR>          viirs_snnp
               2 File(s)     79,618,304 bytes
               4 Dir(s)  52,158,771,200 bytes free