# Creating wildfire dataset for any country using global satellite data #
## We are using country Nepal as our target country  in this example ##

## Data Collection ##
- Please Visit https://firms.modaps.eosdis.nasa.gov/download/ to download both MODIS (2000-2020) and VIIRS (2012-2020) datasets based on each country wildfire data
  - MODIS - https://firms.modaps.eosdis.nasa.gov/country/
  - VIIRS - https://firms.modaps.eosdis.nasa.gov/country/
  - Active Fire (24 Hours, 48 Hours, 7 days)-  https://firms.modaps.eosdis.nasa.gov/usfs/active_fire/

<div style="max-width:400px;">
    <img src="https://github.com/prodramp/wildfire/blob/main/images/disclaimer.png?raw=true" size="400px"/>
</div>

In [1]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
import random
InteractiveShell.ast_node_interactivity = "all"
import os
from datetime import datetime
import plotly.express as px
import glob
from tqdm import tqdm
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 8E69-9D46

 Directory of C:\Users\Sawan\Documents

14-03-2023  11:23    <DIR>          .
14-03-2023  08:59    <DIR>          ..
13-03-2023  20:48    <DIR>          .ipynb_checkpoints
13-03-2023  21:09    <DIR>          dataset
07-03-2023  14:43    <DIR>          OneNote Notebooks
07-03-2023  00:19    <DIR>          Python Scripts
07-03-2023  14:49            13,795 Untitled.ipynb
30-03-2022  02:17           300,738 wildfire_data_creation-nepal.ipynb
14-03-2023  11:19           276,236 Wildfire_data_creation.ipynb
               3 File(s)        590,769 bytes
               6 Dir(s)  57,270,419,456 bytes free

In [3]:
%cd dataset

C:\Users\Sawan\Documents\dataset

In [6]:
%cd dataset

[WinError 2] The system cannot find the file specified: 'dataset'
C:\Users\Sawan\Documents\dataset

In [7]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 8E69-9D46

 Directory of C:\Users\Sawan\Documents\dataset

13-03-2023  21:09    <DIR>          .
14-03-2023  11:26    <DIR>          ..
13-03-2023  21:08    <DIR>          modis
13-03-2023  21:20    <DIR>          viirs_snnp
               0 File(s)              0 bytes
               4 Dir(s)  57,129,054,208 bytes free

In [9]:
all_csv_files

['C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Afghanistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Albania.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Algeria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Angola.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Argentina.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Armenia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Australia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Austria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Azerbaijan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bahamas.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bangladesh.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Belarus.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Belgium.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Belize.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Benin.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bhutan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bolivia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bosnia_and_Herzegovina.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Botswana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Brazil.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Bulgaria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Burkina_Faso.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Burundi.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Cambodia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Cameroon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Canada.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Central_African_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Chad.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Chile.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_China.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Colombia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Costa_Rica.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Cote_d_Ivoire.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Croatia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Cuba.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Curacao.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Cyprus.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Czech_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Democratic_Republic_of_the_Congo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Dem_Rep_Korea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Dominican_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Ecuador.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Egypt.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_El_Salvador.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Equatorial_Guinea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Eritrea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Ethiopia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Fiji.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_France.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_French_Guiana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_French_Polynesia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Gabon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Georgia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Germany.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Ghana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Greece.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Guatemala.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Guinea-Bissau.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Guinea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Guyana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Haiti.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Heard_I_and_McDonald_Islands.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Honduras.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Hungary.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Indonesia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Iran.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Iraq.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Israel.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Italy.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Jamaica.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Japan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Jordan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Kazakhstan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Kenya.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Kosovo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Kuwait.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Kyrgyzstan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Lao_PDR.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Lebanon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Liberia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Libya.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Luxembourg.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Macedonia_Former_Yugoslav_Republic_of.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Madagascar.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Malawi.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Malaysia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Maldives.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Mali.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Mauritania.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Mauritius.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Mexico.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Moldova.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Montenegro.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Montserrat.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Morocco.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Mozambique.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Myanmar.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Namibia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Netherlands.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_New_Caledonia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_New_Zealand.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Nicaragua.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Niger.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Nigeria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Oman.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Pakistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Palestine.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Panama.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Papua_New_Guinea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Paraguay.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Peru.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Philippines.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Poland.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Portugal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Puerto_Rico.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Qatar.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Republic_of_Congo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Republic_of_Korea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Reunion.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Romania.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Russian_Federation.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Rwanda.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Samoa.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Saudi_Arabia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Senegal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Serbia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Sierra_Leone.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Slovakia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Solomon_Islands.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Somalia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_South_Africa.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_South_Sudan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Spain.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Sri_Lanka.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Sudan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Suriname.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Swaziland.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Syria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Taiwan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Tajikistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Tanzania.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Thailand.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_The_Gambia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Timor-Leste.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Togo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Trinidad_and_Tobago.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Turkey.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Turkmenistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Uganda.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Ukraine.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_United_Arab_Emirates.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_United_Kingdom.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_United_States.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Uruguay.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Uzbekistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Vanuatu.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Venezuela.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Vietnam.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Yemen.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Zambia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Zimbabwe.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Afghanistan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Albania.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Algeria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Andorra.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Angola.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Argentina.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Armenia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Australia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Austria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Azerbaijan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bahamas.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bangladesh.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Barbados.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Belarus.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Belgium.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Belize.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Benin.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bhutan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bolivia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bosnia_and_Herzegovina.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Botswana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Brazil.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Brunei_Darussalam.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Bulgaria.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Burkina_Faso.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Burundi.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cambodia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cameroon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Canada.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cape_Verde.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Central_African_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Chad.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Chile.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_China.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Colombia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Comoros.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Costa_Rica.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cote_d_Ivoire.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Croatia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cuba.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Curacao.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Cyprus.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Czech_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Democratic_Republic_of_the_Congo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Dem_Rep_Korea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Denmark.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Djibouti.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Dominica.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Dominican_Republic.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Ecuador.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Egypt.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_El_Salvador.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Equatorial_Guinea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Eritrea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Estonia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Ethiopia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Falkland_Islands.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Fiji.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Finland.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_France.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_French_Guiana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_French_Polynesia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Gabon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Georgia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Germany.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Ghana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Greece.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Greenland.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guadeloupe.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guam.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guatemala.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guinea-Bissau.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guinea.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Guyana.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Haiti.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Honduras.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Hong_Kong.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Hungary.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_India.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Indonesia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Iran.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Iraq.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Ireland.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Israel.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Italy.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Jamaica.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Japan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Jordan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Kazakhstan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Kenya.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Kosovo.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Kuwait.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Kyrgyzstan.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Lao_PDR.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Latvia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Lebanon.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Lesotho.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Liberia.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Libya.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Lithuania.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Luxembourg.csv',

In [8]:
all_csv_files = glob.glob('C:/Users/Sawan/Documents/dataset/**/*.csv', recursive=True)

In [10]:
len(all_csv_files)

6635

In [11]:
type(all_csv_files)

list

In [ ]:
# all_us_files = list(filter(lambda k: 'United_States' in k, all_csv_file))

In [15]:
all_nepal_files = list(filter(lambda k: 'Nepal' in k, all_csv_files))

In [11]:
all_nepal_files

['../wildfire-data/viirs-snpp/2013/viirs-snpp_2013_Nepal.csv',
 '../wildfire-data/viirs-snpp/2014/viirs-snpp_2014_Nepal.csv',
 '../wildfire-data/viirs-snpp/2015/viirs-snpp_2015_Nepal.csv',
 '../wildfire-data/viirs-snpp/2012/viirs-snpp_2012_Nepal.csv',
 '../wildfire-data/viirs-snpp/2017/viirs-snpp_2017_Nepal.csv',
 '../wildfire-data/viirs-snpp/2019/viirs-snpp_2019_Nepal.csv',
 '../wildfire-data/viirs-snpp/2021/viirs-snpp_2021_Nepal.csv',
 '../wildfire-data/viirs-snpp/2020/viirs-snpp_2020_Nepal.csv',
 '../wildfire-data/viirs-snpp/2018/viirs-snpp_2018_Nepal.csv',
 '../wildfire-data/viirs-snpp/2016/viirs-snpp_2016_Nepal.csv',
 '../wildfire-data/modis/2013/modis_2013_Nepal.csv',
 '../wildfire-data/modis/2014/modis_2014_Nepal.csv',
 '../wildfire-data/modis/2015/modis_2015_Nepal.csv',
 '../wildfire-data/modis/2012/modis_2012_Nepal.csv',
 '../wildfire-data/modis/2008/modis_2008_Nepal.csv',
 '../wildfire-data/modis/2001/modis_2001_Nepal.csv',
 '../wildfire-data/modis/2006/modis_2006_Nepal.csv',
 '../wildfire-data/modis/2007/modis_2007_Nepal.csv',
 '../wildfire-data/modis/2000/modis_2000_Nepal.csv',
 '../wildfire-data/modis/2009/modis_2009_Nepal.csv',
 '../wildfire-data/modis/2017/modis_2017_Nepal.csv',
 '../wildfire-data/modis/2010/modis_2010_Nepal.csv',
 '../wildfire-data/modis/2019/modis_2019_Nepal.csv',
 '../wildfire-data/modis/2020/modis_2020_Nepal.csv',
 '../wildfire-data/modis/2018/modis_2018_Nepal.csv',
 '../wildfire-data/modis/2011/modis_2011_Nepal.csv',
 '../wildfire-data/modis/2016/modis_2016_Nepal.csv',
 '../wildfire-data/modis/2005/modis_2005_Nepal.csv',
 '../wildfire-data/modis/2002/modis_2002_Nepal.csv',
 '../wildfire-data/modis/2003/modis_2003_Nepal.csv',
 '../wildfire-data/modis/2004/modis_2004_Nepal.csv']

In [16]:
all_nepal_files = list(filter(lambda k: 'Nepal.csv' in k, all_csv_files))

In [17]:
all_nepal_files

['C:/Users/Sawan/Documents/dataset\\modis\\2000\\modis_2000_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2001\\modis_2001_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2002\\modis_2002_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2003\\modis_2003_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2004\\modis_2004_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2005\\modis_2005_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2006\\modis_2006_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2007\\modis_2007_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2008\\modis_2008_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2009\\modis_2009_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2010\\modis_2010_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2011\\modis_2011_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2012\\modis_2012_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2013\\modis_2013_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2014\\modis_2014_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2015\\modis_2015_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2016\\modis_2016_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2017\\modis_2017_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2018\\modis_2018_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2019\\modis_2019_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2020\\modis_2020_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\modis\\2021\\modis_2021_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2012\\viirs-snpp_2012_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2013\\viirs-snpp_2013_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2014\\viirs-snpp_2014_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2015\\viirs-snpp_2015_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2016\\viirs-snpp_2016_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2017\\viirs-snpp_2017_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2018\\viirs-snpp_2018_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2019\\viirs-snpp_2019_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2020\\viirs-snpp_2020_Nepal.csv',
 'C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2021\\viirs-snpp_2021_Nepal.csv']

In [18]:
df_viirs = pd.read_csv('C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2020\\viirs-snpp_2020_Nepal.csv')

In [19]:
df_viirs = pd.read_csv('C:/Users/Sawan/Documents/dataset\\viirs_snnp\\2020\\viirs-snpp_2020_Nepal.csv', low_memory=False)

In [20]:
df_viirs

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight,type
0,27.532799,83.409477,295.24,0.39,0.36,2020-01-04,2007,N,VIIRS,n,1,283.93,0.48,N,0
1,29.014025,82.741753,325.50,0.40,0.44,2020-01-11,710,N,VIIRS,l,1,296.50,3.10,D,0
2,28.972002,82.721237,329.05,0.40,0.44,2020-01-11,710,N,VIIRS,n,1,298.24,4.61,D,0
3,28.967470,82.850662,299.74,0.32,0.55,2020-01-11,1935,N,VIIRS,n,1,273.13,0.49,N,0
4,28.964066,82.850983,299.47,0.32,0.55,2020-01-11,1935,N,VIIRS,n,1,273.02,0.78,N,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9245,28.328114,84.929863,329.22,0.48,0.40,2020-12-31,2018,N,VIIRS,n,1,281.11,5.99,0,0
9246,28.331739,84.930809,324.43,0.48,0.40,2020-12-31,2018,N,VIIRS,n,1,279.79,2.50,0,0
9247,29.692017,81.372002,306.27,0.38,0.36,2020-12-31,2018,N,VIIRS,n,1,264.39,1.06,0,0
9248,28.328835,84.926025,327.65,0.48,0.40,2020-12-31,2018,N,VIIRS,n,1,283.64,9.41,0,0
9249,28.327314,84.927071,332.61,0.48,0.40,2020-12-31,2018,N,VIIRS,n,1,280.17,6.07,0,0

In [21]:
df_viirs['satellite'].unique()

array(['N'], dtype=object)

In [22]:
df_viirs['instrument'].unique()

array(['VIIRS'], dtype=object)

In [23]:
type(df_viirs.confidence[0])

str

In [24]:
isinstance(df_viirs.confidence[0], str)

True

In [25]:
df_viirs.confidence.unique()

array(['n', 'l', 'h'], dtype=object)

In [26]:
df_modis = pd.read_csv( 'C:/Users/Sawan/Documents/dataset\\modis\\2020\\modis_2020_Nepal.csv')

In [27]:
df_modis

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,28.5115,81.2492,300.0,1.5,1.2,2020-01-13,734,Aqua,MODIS,24,6.03,288.2,6.7,D,0
1,28.5604,82.7200,305.1,1.2,1.1,2020-01-13,734,Aqua,MODIS,45,6.03,294.2,8.2,D,0
2,26.6773,86.9825,317.9,1.1,1.1,2020-01-15,721,Aqua,MODIS,77,6.03,295.8,14.0,D,0
3,28.3409,84.4350,304.1,1.0,1.0,2020-01-20,740,Aqua,MODIS,58,6.03,282.9,8.3,D,0
4,28.6669,82.7348,307.1,1.5,1.2,2020-01-22,728,Aqua,MODIS,53,6.03,284.5,16.1,D,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1347,28.3312,84.4264,304.0,3.2,1.7,2020-12-31,817,Aqua,MODIS,57,6.03,292.6,34.2,D,0
1348,28.6429,82.7774,312.2,2.4,1.5,2020-12-31,817,Aqua,MODIS,31,6.03,300.9,32.2,D,0
1349,28.6385,82.7702,309.7,2.4,1.5,2020-12-31,817,Aqua,MODIS,49,6.03,299.0,25.0,D,0
1350,29.8585,81.2090,301.9,2.0,1.4,2020-12-31,817,Aqua,MODIS,36,6.03,283.6,21.1,D,0
1351,28.3304,84.9318,302.5,1.1,1.1,2020-12-31,2023,Aqua,MODIS,50,6.03,279.1,11.2,N,0

In [28]:
df_modis['satellite'].unique()

array(['Aqua', 'Terra'], dtype=object)

In [29]:
df_modis['instrument'].unique()

array(['MODIS'], dtype=object)

In [30]:
type(df_modis['confidence'][0])

numpy.int64

In [31]:
df_modis['confidence'].unique()

array([ 24,  45,  77,  58,  53,  72,  66,  50,  48,  37,  71,  41,  44,
        21,  26,  63,  51,  61,  43,  67,  59,  62,  73,  64,   0,  76,
        47,  54,  65,  69,  38,  29,  52,  60,  82,  32,  74,  42,  55,
        68,  19,  49,  57,  15,  35,  36,  85,  14,  78,  17,  81,  25,
        83,  84,  75,  94,  92,  93,  70,  80,  56,  40,  95,  86,  31,
        39,  22,  79,  12,  27,  90,  10, 100,  33,  30,  34,  89,  46,
        96,  87,  88,  18,  28,  91,   7,  23,  16,  97,  99,  20,  11,
        98,  13], dtype=int64)

In [32]:
# Taken this idea from the H2O.ai wild fire competition github repo and changed it meet the local need
rows = []
fire_df = []
row_sum = 0
for f in tqdm(all_nepal_files):
    df = pd.read_csv(f, parse_dates=['acq_time'], low_memory=False) 
    csv_name = f.split('/')[-1]
    row = [
        f, csv_name, df.shape[0], df.shape[1], df.acq_date.min(), df.acq_date.max(),
        df.satellite.unique(), df.instrument.max(), df.version.max(),
        df.latitude.nunique(), df.longitude.nunique(),
        df.confidence.nunique(), df.satellite.nunique(), df.acq_date.nunique()
    ]
    if isinstance(df.confidence[0], str):
        df.confidence = df.confidence.replace({'l': 0, 'n': 50, 'h': 100})
    rows.append(row)
    row_sum = row_sum + df.shape[0]
    fire_df.append(df)
cols = [
    'path', 'csv', 'rows', 'cols', 'start', 'end',
    'satellite', 'instrument', 'version',
    'lats', 'lons', 'confs', 'sats', 'days'
]
filestats = pd.DataFrame(rows, columns=cols)
filestats.sort_values(by=['start', 'instrument'])
print("Total Rows: " + str(row_sum))

100%|██████████████████████████████████████████████████████████████████████████████████| 32/32 [00:01<00:00, 25.03it/s]

,path,csv,rows,cols,start,end,satellite,instrument,version,lats,lons,confs,sats,days
0,C:/Users/Sawan/Documents/dataset\modis\2000\mo...,dataset\modis\2000\modis_2000_Nepal.csv,98,15,2000-11-01,2000-12-29,[Terra],MODIS,6.20,98,98,57,1,34
1,C:/Users/Sawan/Documents/dataset\modis\2001\mo...,dataset\modis\2001\modis_2001_Nepal.csv,1238,15,2001-01-02,2001-12-29,[Terra],MODIS,6.20,1207,1222,91,1,139
2,C:/Users/Sawan/Documents/dataset\modis\2002\mo...,dataset\modis\2002\modis_2002_Nepal.csv,487,15,2002-01-01,2002-12-30,"[Terra, Aqua]",MODIS,6.20,479,480,88,2,121
3,C:/Users/Sawan/Documents/dataset\modis\2003\mo...,dataset\modis\2003\modis_2003_Nepal.csv,2202,15,2003-01-03,2003-12-31,"[Terra, Aqua]",MODIS,6.20,2091,2144,94,2,210
4,C:/Users/Sawan/Documents/dataset\modis\2004\mo...,dataset\modis\2004\modis_2004_Nepal.csv,2846,15,2004-01-02,2004-12-30,"[Terra, Aqua]",MODIS,6.20,2682,2772,97,2,178
5,C:/Users/Sawan/Documents/dataset\modis\2005\mo...,dataset\modis\2005\modis_2005_Nepal.csv,2676,15,2005-01-02,2005-12-31,"[Terra, Aqua]",MODIS,6.20,2540,2602,95,2,203
6,C:/Users/Sawan/Documents/dataset\modis\2006\mo...,dataset\modis\2006\modis_2006_Nepal.csv,2349,15,2006-01-01,2006-12-31,"[Terra, Aqua]",MODIS,6.20,2218,2296,95,2,178
7,C:/Users/Sawan/Documents/dataset\modis\2007\mo...,dataset\modis\2007\modis_2007_Nepal.csv,1353,15,2007-01-02,2007-12-31,"[Aqua, Terra]",MODIS,6.20,1306,1332,90,2,172
8,C:/Users/Sawan/Documents/dataset\modis\2008\mo...,dataset\modis\2008\modis_2008_Nepal.csv,2990,15,2008-01-01,2008-12-31,"[Terra, Aqua]",MODIS,6.20,2792,2896,95,2,190
9,C:/Users/Sawan/Documents/dataset\modis\2009\mo...,dataset\modis\2009\modis_2009_Nepal.csv,4704,15,2009-01-03,2009-12-31,"[Aqua, Terra]",MODIS,6.20,4287,4508,95,2,209
10,C:/Users/Sawan/Documents/dataset\modis\2010\mo...,dataset\modis\2010\modis_2010_Nepal.csv,3242,15,2010-01-01,2010-12-31,"[Aqua, Terra]",MODIS,6.20,3027,3154,98,2,184
11,C:/Users/Sawan/Documents/dataset\modis\2011\mo...,dataset\modis\2011\modis_2011_Nepal.csv,1908,15,2011-01-02,2011-12-31,"[Aqua, Terra]",MODIS,6.20,1821,1878,97,2,180
12,C:/Users/Sawan/Documents/dataset\modis\2012\mo...,dataset\modis\2012\modis_2012_Nepal.csv,3581,15,2012-01-05,2012-12-31,"[Aqua, Terra]",MODIS,6.20,3333,3457,97,2,213
22,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2012\viirs-snpp_2012_Nepal.csv,31490,15,2012-01-20,2012-12-31,[N],VIIRS,1.00,30984,30739,3,1,226
13,C:/Users/Sawan/Documents/dataset\modis\2013\mo...,dataset\modis\2013\modis_2013_Nepal.csv,2534,15,2013-01-01,2013-12-30,"[Terra, Aqua]",MODIS,6.20,2371,2470,97,2,174
23,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2013\viirs-snpp_2013_Nepal.csv,22665,15,2013-01-01,2013-12-31,[N],VIIRS,1.00,22429,22275,3,1,216
14,C:/Users/Sawan/Documents/dataset\modis\2014\mo...,dataset\modis\2014\modis_2014_Nepal.csv,3443,15,2014-01-01,2014-12-31,"[Aqua, Terra]",MODIS,6.20,3212,3361,97,2,196
24,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2014\viirs-snpp_2014_Nepal.csv,35244,15,2014-01-01,2014-12-31,[N],VIIRS,1.00,34695,34490,3,1,228
25,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2015\viirs-snpp_2015_Nepal.csv,8669,15,2015-01-06,2015-12-31,[N],VIIRS,1.00,8629,8596,3,1,235
15,C:/Users/Sawan/Documents/dataset\modis\2015\mo...,dataset\modis\2015\modis_2015_Nepal.csv,1083,15,2015-01-13,2015-12-31,"[Aqua, Terra]",MODIS,6.20,1047,1075,88,2,177
16,C:/Users/Sawan/Documents/dataset\modis\2016\mo...,dataset\modis\2016\modis_2016_Nepal.csv,7767,15,2016-01-01,2016-12-31,"[Terra, Aqua]",MODIS,6.20,6655,7259,100,2,193
26,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2016\viirs-snpp_2016_Nepal.csv,62025,15,2016-01-01,2016-12-31,[N],VIIRS,1.00,60216,59437,3,1,234
27,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2017\viirs-snpp_2017_Nepal.csv,17721,15,2017-01-01,2017-12-31,[N],VIIRS,1.00,17579,17478,3,1,233
17,C:/Users/Sawan/Documents/dataset\modis\2017\mo...,dataset\modis\2017\modis_2017_Nepal.csv,2218,15,2017-01-02,2017-12-31,"[Aqua, Terra]",MODIS,6.20,2106,2168,94,2,192
18,C:/Users/Sawan/Documents/dataset\modis\2018\mo...,dataset\modis\2018\modis_2018_Nepal.csv,2990,15,2018-01-01,2018-12-31,"[Aqua, Terra]",MODIS,6.03,2789,2892,98,2,203
28,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2018\viirs-snpp_2018_Nepal.csv,21996,15,2018-01-01,2018-12-31,[N],VIIRS,1.00,21790,21615,3,1,243
19,C:/Users/Sawan/Documents/dataset\modis\2019\mo...,dataset\modis\2019\modis_2019_Nepal.csv,3950,15,2019-01-01,2019-12-31,"[Aqua, Terra]",MODIS,6.03,3607,3773,99,2,186
29,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2019\viirs-snpp_2019_Nepal.csv,31299,15,2019-01-01,2019-12-31,[N],VIIRS,1.00,30800,30442,3,1,248
30,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2020\viirs-snpp_2020_Nepal.csv,9250,15,2020-01-04,2020-12-31,[N],VIIRS,1.00,9222,9173,3,1,223
20,C:/Users/Sawan/Documents/dataset\modis\2020\mo...,dataset\modis\2020\modis_2020_Nepal.csv,1352,15,2020-01-13,2020-12-31,"[Aqua, Terra]",MODIS,6.03,1314,1329,93,2,173
21,C:/Users/Sawan/Documents/dataset\modis\2021\mo...,dataset\modis\2021\modis_2021_Nepal.csv,8235,15,2021-01-01,2021-12-25,"[Terra, Aqua]",MODIS,6.03,7062,7697,99,2,173
31,C:/Users/Sawan/Documents/dataset\viirs_snnp\20...,dataset\viirs_snnp\2021\viirs-snpp_2021_Nepal.csv,60358,15,2021-01-01,2021-12-31,[N],VIIRS,1.00,58649,57891,3,1,212

Total Rows: 363963

In [33]:
fire_df

[    latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0    27.5921    87.5385       306.2   1.1    1.1  2000-11-01     0500
 1    29.1006    81.9170       330.6   1.3    1.1  2000-11-06     0518
 2    30.0881    81.3358       308.7   1.8    1.3  2000-11-07     0601
 3    30.0841    81.3570       306.0   1.9    1.3  2000-11-07     0601
 4    30.1060    81.9647       315.0   2.1    1.4  2000-11-08     0506
 ..       ...        ...         ...   ...    ...         ...      ...
 93   28.4087    84.4653       307.7   1.3    1.1  2000-12-29     0536
 94   28.4061    84.4805       314.7   1.3    1.1  2000-12-29     0536
 95   28.3960    82.9464       302.2   1.1    1.0  2000-12-29     0536
 96   26.6550    86.9884       314.2   1.0    1.0  2000-12-29     1634
 97   26.6535    86.9783       316.9   1.0    1.0  2000-12-29     1634

    satellite instrument  confidence  version  bright_t31   frp daynight  type
 0      Terra      MODIS          55      6.2       292.1   6.2        D     0
 1      Terra      MODIS          87      6.2       293.7  43.0        D     0
 2      Terra      MODIS          58      6.2       291.2  21.1        D     0
 3      Terra      MODIS          37      6.2       287.4  17.1        D     0
 4      Terra      MODIS          64      6.2       282.6  41.6        D     0
 ..       ...        ...         ...      ...         ...   ...      ...   ...
 93     Terra      MODIS          63      6.2       282.1  14.4        D     0
 94     Terra      MODIS          75      6.2       286.3  22.0        D     0
 95     Terra      MODIS          47      6.2       283.5   8.1        D     0
 96     Terra      MODIS          89      6.2       282.8  16.6        N     0
 97     Terra      MODIS          94      6.2       282.2  18.9        N     0

 [98 rows x 15 columns],
       latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0      26.7050    87.0302       327.0   1.0    1.0  2001-01-02     0512
 1      26.6904    87.0006       310.9   1.0    1.0  2001-01-02     0512
 2      27.6438    86.5643       303.7   2.3    1.5  2001-01-05     0542
 3      27.6330    86.5584       300.4   2.3    1.5  2001-01-05     0542
 4      28.3794    84.3932       305.1   1.0    1.0  2001-01-09     0517
 ...        ...        ...         ...   ...    ...         ...      ...
 1233   28.5240    82.9213       303.9   1.0    1.0  2001-12-25     0520
 1234   28.5225    82.9313       310.3   1.0    1.0  2001-12-25     0520
 1235   28.3911    84.0333       300.3   1.0    1.0  2001-12-27     0508
 1236   29.1916    82.6566       314.0   2.4    1.5  2001-12-28     0551
 1237   29.2189    82.6293       304.7   1.9    1.3  2001-12-29     0456

      satellite instrument  confidence  version  bright_t31   frp daynight  \
 0        Terra      MODIS          83      6.2       296.4  20.2        D
 1        Terra      MODIS          53      6.2       293.1   7.2        D
 2        Terra      MODIS          57      6.2       279.3  28.4        D
 3        Terra      MODIS          33      6.2       278.2  21.6        D
 4        Terra      MODIS          49      6.2       292.4   7.5        D
 ...        ...        ...         ...      ...         ...   ...      ...
 1233     Terra      MODIS          38      6.2       289.6   7.4        D
 1234     Terra      MODIS          36      6.2       299.0  11.1        D
 1235     Terra      MODIS          22      6.2       283.2   6.0        D
 1236     Terra      MODIS          74      6.2       275.4  59.3        D
 1237     Terra      MODIS          39      6.2       284.3  16.5        D

       type
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 1233     0
 1234     0
 1235     0
 1236     0
 1237     0

 [1238 rows x 15 columns],
      latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0     28.3735    84.6135       316.2   1.3    1.1  2002-01-01     0526
 1     29.7648    82.1874       314.2   1.0    1.0  2002-01-01     0526
 2     28.3714    84.6255       305.9   1.3    1.1  2002-01-01     0526
 3     28.5939    84.3690       308.5   3.8    1.8  2002-01-02     0431
 4     28.9111    83.0308       304.6   4.7    2.0  2002-01-02     0431
 ..        ...        ...         ...   ...    ...         ...      ...
 482   28.9471    82.5956       310.4   1.2    1.1  2002-12-29     0731
 483   28.0165    85.7597       305.3   1.0    1.0  2002-12-30     0506
 484   28.5069    84.8030       305.0   1.0    1.0  2002-12-30     0506
 485   28.5430    83.7412       305.5   2.8    1.6  2002-12-30     0814
 486   28.5440    83.7335       307.7   2.8    1.6  2002-12-30     0814

     satellite instrument  confidence  version  bright_t31   frp daynight  type
 0       Terra      MODIS          74      6.2       281.7  25.5        D     0
 1       Terra      MODIS          63      6.2       283.7  15.5        D     0
 2       Terra      MODIS          46      6.2       283.0  14.7        D     0
 3       Terra      MODIS          67      6.2       277.0  70.3        D     0
 4       Terra      MODIS          40      6.2       275.4  72.0        D     0
 ..        ...        ...         ...      ...         ...   ...      ...   ...
 482      Aqua      MODIS          70      6.2       284.0  17.2        D     0
 483     Terra      MODIS          42      6.2       285.0   8.2        D     0
 484     Terra      MODIS          60      6.2       277.6  11.1        D     0
 485      Aqua      MODIS          40      6.2       286.9  34.7        D     0
 486      Aqua      MODIS          57      6.2       287.4  42.4        D     0

 [487 rows x 15 columns],
       latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0      27.4748    87.3259       303.6   1.4    1.2  2003-01-03     0442
 1      27.8566    82.6954       304.7   1.0    1.0  2003-01-03     0749
 2      28.2973    84.9239       316.6   1.4    1.2  2003-01-04     0524
 3      27.7935    87.4363       303.7   2.2    1.5  2003-01-05     0429
 4      27.7907    87.4661       319.1   2.2    1.4  2003-01-05     0429
 ...        ...        ...         ...   ...    ...         ...      ...
 2197   29.8979    82.2802       310.1   1.5    1.2  2003-12-25     0726
 2198   27.4643    86.9112       302.2   1.0    1.0  2003-12-26     0500
 2199   29.3883    80.9689       306.5   1.1    1.0  2003-12-29     0531
 2200   26.6570    86.9757       303.3   1.3    1.2  2003-12-30     0743
 2201   28.3883    84.8847       303.8   1.2    1.1  2003-12-31     0518

      satellite instrument  confidence  version  bright_t31   frp daynight  \
 0        Terra      MODIS          49      6.2       290.2   9.0        D
 1         Aqua      MODIS          60      6.2       294.7   4.3        D
 2        Terra      MODIS          77      6.2       284.6  26.7        D
 3        Terra      MODIS          40      6.2       286.7  23.9        D
 4        Terra      MODIS          79      6.2       284.8  60.3        D
 ...        ...        ...         ...      ...         ...   ...      ...
 2197      Aqua      MODIS          69      6.2       279.3  22.3        D
 2198     Terra      MODIS          34      6.2       287.7   8.1        D
 2199     Terra      MODIS          44      6.2       290.5   8.4        D
 2200      Aqua      MODIS          53      6.2       292.7   5.4        D
 2201     Terra      MODIS          50      6.2       287.7   9.1        D

       type
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 2197     0
 2198     0
 2199     0
 2200     0
 2201     0

 [2202 rows x 15 columns],
       latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0      29.7984    82.1262       302.5   1.3    1.1  2004-01-02     0506
 1      28.7502    82.6944       306.0   1.2    1.1  2004-01-02     0506
 2      28.2591    84.8180       309.4   1.0    1.0  2004-01-02     0506
 3      28.2577    84.8278       306.5   1.0    1.0  2004-01-02     0506
 4      28.9584    82.6542       301.0   1.2    1.1  2004-01-02     0506
 ...        ...        ...         ...   ...    ...         ...      ...
 2841   29.6730    81.2428       304.2   1.5    1.2  2004-12-29     0541
 2842   29.6750    81.2317       302.5   1.5    1.2  2004-12-29     0541
 2843   29.6689    81.2375       305.7   1.5    1.2  2004-12-29     0541
 2844   26.7015    87.0134       308.6   2.2    1.4  2004-12-30     0755
 2845   26.7028    87.0182       305.6   2.2    1.4  2004-12-30     0755

      satellite instrument  confidence  version  bright_t31   frp daynight  \
 0        Terra      MODIS          41      6.2       279.0  11.5        D
 1        Terra      MODIS          44      6.2       287.8  10.5        D
 2        Terra      MODIS          67      6.2       279.4  11.6        D
 3        Terra      MODIS          60      6.2       281.8   9.7        D
 4        Terra      MODIS          36      6.2       290.9   9.5        D
 ...        ...        ...         ...      ...         ...   ...      ...
 2841     Terra      MODIS          58      6.2       285.3  12.2        D
 2842     Terra      MODIS          42      6.2       286.2   9.8        D
 2843     Terra      MODIS          51      6.2       285.8  12.5        D
 2844      Aqua      MODIS          33      6.2       291.5  20.8        D
 2845      Aqua      MODIS          22      6.2       289.9  14.3        D

       type
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 2841     0
 2842     0
 2843     0
 2844     0
 2845     0

 [2846 rows x 15 columns],
       latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0      29.0468    81.9065       301.4   1.0    1.0  2005-01-02     0516
 1      28.8066    80.1287       307.9   2.6    1.6  2005-01-02     0827
 2      28.8005    80.1374       310.6   2.6    1.6  2005-01-02     0827
 3      28.7276    83.6603       305.8   1.1    1.0  2005-01-04     0504
 4      28.7336    83.6675       317.5   1.1    1.0  2005-01-04     0504
 ...        ...        ...         ...   ...    ...         ...      ...
 2671   28.4021    84.8768       329.3   1.1    1.0  2005-12-31     0458
 2672   28.5517    83.7110       313.7   1.3    1.1  2005-12-31     0458
 2673   28.3929    84.8748       327.5   1.1    1.0  2005-12-31     0458
 2674   27.5570    84.4695       305.5   2.4    1.5  2005-12-31     0807
 2675   27.5474    84.4510       304.6   2.4    1.5  2005-12-31     0807

      satellite instrument  confidence  version  bright_t31   frp daynight  \
 0        Terra      MODIS          28      6.2       290.3   6.9        D
 1         Aqua      MODIS          64      6.2       294.0  22.4        D
 2         Aqua      MODIS          68      6.2       294.4  30.4        D
 3        Terra      MODIS          44      6.2       292.4   9.1        D
 4        Terra      MODIS          75      6.2       290.1  17.4        D
 ...        ...        ...         ...      ...         ...   ...      ...
 2671     Terra      MODIS          82      6.2       299.2  29.1        D
 2672     Terra      MODIS          56      6.2       293.3  15.3        D
 2673     Terra      MODIS          80      6.2       294.8  25.9        D
 2674      Aqua      MODIS          58      6.2       294.2  17.7        D
 2675      Aqua      MODIS          43      6.2       294.3  15.9        D

       type
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 2671     0
 2672     0
 2673     0
 2674     0
 2675     0

 [2676 rows x 15 columns],
       latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0      28.0178    85.8579       302.3   3.3    1.7  2006-01-01     0540
 1      28.2981    84.8611       305.3   1.7    1.3  2006-01-01     0712
 2      28.3099    84.8711       301.3   1.7    1.3  2006-01-01     0712
 3      28.2808    84.7034       307.0   1.8    1.3  2006-01-01     0712
 4      27.7515    87.3802       308.2   1.2    1.1  2006-01-01     0712
 ...        ...        ...         ...   ...    ...         ...      ...
 2344   29.5835    82.4793       317.0   1.1    1.0  2006-12-29     0752
 2345   29.1087    82.1382       300.9   1.0    1.0  2006-12-30     0523
 2346   26.6880    87.0357       310.1   1.1    1.1  2006-12-31     0739
 2347   29.2324    82.0293       316.6   1.1    1.0  2006-12-31     0740
 2348   29.4390    81.6450       302.0   1.1    1.1  2006-12-31     0740

      satellite instrument  confidence  version  bright_t31   frp daynight  \
 0        Terra      MODIS          52      6.2       280.8  39.2        D
 1         Aqua      MODIS          56      6.2       285.0  16.0        D
 2         Aqua      MODIS          26      6.2       285.0  11.5        D
 3         Aqua      MODIS          60      6.2       285.8  17.6        D
 4         Aqua      MODIS          50      6.2       294.4  10.9        D
 ...        ...        ...         ...      ...         ...   ...      ...
 2344      Aqua      MODIS          54      6.2       299.0  15.8        D
 2345     Terra      MODIS          33      6.2       288.7   6.5        D
 2346      Aqua      MODIS          47      6.2       295.9   6.9        D
 2347      Aqua      MODIS          46      6.2       301.4  12.5        D
 2348      Aqua      MODIS          44      6.2       289.3   7.5        D

       type
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 2344     0
 2345     0
 2346     0
 2347     0
 2348     0

 [2349 rows x 15 columns],
       latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0      28.3403    84.8504       300.8   1.1    1.1  2007-01-02     0727
 1      28.3387    84.8403       302.6   1.1    1.1  2007-01-02     0727
 2      28.2405    84.7899       303.1   1.1    1.1  2007-01-03     0459
 3      28.4983    83.7131       304.1   2.2    1.4  2007-01-03     0810
 4      29.1918    82.8444       318.8   2.0    1.4  2007-01-03     0811
 ...        ...        ...         ...   ...    ...         ...      ...
 1348   28.4641    84.3920       314.3   2.3    1.5  2007-12-31     0709
 1349   28.4564    84.4207       313.7   2.3    1.5  2007-12-31     0709
 1350   28.4675    84.4017       302.9   2.3    1.5  2007-12-31     0709
 1351   28.4536    84.3998       325.2   2.3    1.5  2007-12-31     0709
 1352   28.4594    84.4293       305.3   2.3    1.5  2007-12-31     0709

      satellite instrument  confidence  version  bright_t31   frp daynight  \
 0         Aqua      MODIS          17      6.2       285.2   7.6        D
 1         Aqua      MODIS          29      6.2       289.8   8.9        D
 2        Terra      MODIS          33      6.2       288.4   6.2        D
 3         Aqua      MODIS          38      6.2       289.2  18.5        D
 4         Aqua      MODIS          58      6.2       296.2  37.2        D
 ...        ...        ...         ...      ...         ...   ...      ...
 1348      Aqua      MODIS          49      6.2       283.9  48.1        D
 1349      Aqua      MODIS          45      6.2       282.3  46.1        D
 1350      Aqua      MODIS          25      6.2       283.6  23.8        D
 1351      Aqua      MODIS          84      6.2       286.9  86.7        D
 1352      Aqua      MODIS          48      6.2       281.2  28.4        D

       type
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 1348     0
 1349     0
 1350     0
 1351     0
 1352     0

 [1353 rows x 15 columns],
       latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0      28.4627    84.4317       311.7   2.2    1.5  2008-01-01     0441
 1      28.0334    85.6662       300.5   1.4    1.2  2008-01-01     0751
 2      28.3590    84.8865       309.9   1.3    1.1  2008-01-01     0751
 3      28.3047    84.9350       330.4   1.3    1.1  2008-01-01     0751
 4      28.4772    84.4159       307.3   1.2    1.1  2008-01-01     0751
 ...        ...        ...         ...   ...    ...         ...      ...
 2985   27.4165    83.7231       308.2   1.0    1.0  2008-12-27     0749
 2986   29.6825    81.2950       325.6   1.4    1.2  2008-12-29     0738
 2987   26.9024    86.0274       313.1   1.0    1.0  2008-12-30     0506
 2988   26.6432    86.9928       322.8   1.1    1.1  2008-12-31     0725
 2989   26.6414    86.9818       317.7   1.1    1.1  2008-12-31     0725

      satellite instrument  confidence  version  bright_t31   frp daynight  \
 0        Terra      MODIS          64      6.2       286.0  33.2        D
 1         Aqua      MODIS          30      6.2       286.1   6.9        D
 2         Aqua      MODIS          62      6.2       291.8  11.6        D
 3         Aqua      MODIS          86      6.2       292.2  41.3        D
 4         Aqua      MODIS          28      6.2       290.6   9.1        D
 ...        ...        ...         ...      ...         ...   ...      ...
 2985      Aqua      MODIS          63      6.2       295.8   4.7        D
 2986      Aqua      MODIS          84      6.2       285.3  39.9        D
 2987     Terra      MODIS          73      6.2       295.0   8.9        D
 2988      Aqua      MODIS          81      6.2       301.7  17.5        D
 2989      Aqua      MODIS          76      6.2       300.0  11.7        D

       type
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 2985     0
 2986     0
 2987     0
 2988     0
 2989     0

 [2990 rows x 15 columns],
       latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0      29.0107    82.7129       334.2   1.1    1.0  2009-01-03     0756
 1      27.3943    83.7459       311.8   1.0    1.0  2009-01-05     0743
 2      26.9405    85.7319       308.9   1.0    1.0  2009-01-05     0743
 3      26.6161    86.9598       317.5   1.1    1.1  2009-01-05     0743
 4      26.9496    85.7303       310.8   1.0    1.0  2009-01-05     0743
 ...        ...        ...         ...   ...    ...         ...      ...
 4699   29.8342    80.9963       300.2   1.9    1.4  2009-12-26     0459
 4700   29.3320    81.4487       302.2   1.6    1.2  2009-12-26     0814
 4701   28.8004    80.1223       304.8   1.0    1.0  2009-12-28     0801
 4702   29.5237    81.5462       302.1   1.1    1.0  2009-12-28     0801
 4703   28.4655    84.8982       313.3   1.7    1.3  2009-12-31     2038

      satellite instrument  confidence  version  bright_t31   frp daynight  \
 0         Aqua      MODIS          73      6.2       302.7  35.0        D
 1         Aqua      MODIS          72      6.2       293.4   9.2        D
 2         Aqua      MODIS          67      6.2       295.4   5.4        D
 3         Aqua      MODIS          75      6.2       299.2  12.4        D
 4         Aqua      MODIS          70      6.2       294.6   6.7        D
 ...        ...        ...         ...      ...         ...   ...      ...
 4699     Terra      MODIS          21      6.2       278.3  12.9        D
 4700      Aqua      MODIS          39      6.2       286.4  12.2        D
 4701      Aqua      MODIS          60      6.2       293.5   5.3        D
 4702      Aqua      MODIS          31      6.2       288.2   7.0        D
 4703      Aqua      MODIS          82      6.2       279.1  36.9        N

       type
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 4699     0
 4700     0
 4701     0
 4702     0
 4703     0

 [4704 rows x 15 columns],
       latitude  longitude  brightness  scan  track    acq_date acq_time  \
 0      28.3435    84.4355       311.8   1.0    1.0  2010-01-01     0736
 1      29.7710    81.7457       302.4   1.3    1.1  2010-01-01     1659
 2      29.7812    81.7438       328.6   1.3    1.1  2010-01-01     1659
 3      29.7825    81.7552       326.3   1.3    1.1  2010-01-01     1659
 4      28.9926    82.4879       309.3   1.2    1.1  2010-01-02     0505
 ...        ...        ...         ...   ...    ...         ...      ...
 3237   28.3554    84.8992       313.8   1.7    1.3  2010-12-30     0716
 3238   28.3578    84.9137       311.6   1.7    1.3  2010-12-30     0716

In [34]:
nepal_fire_df = pd.concat(fire_df)
nepal_fire_df.shape

(363963, 17)

In [35]:
nepal_fire_df.sample(10)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,bright_ti4,bright_ti5
8578,29.834846,82.068077,NaN,0.50,0.66,2020-12-24,0824,N,VIIRS,100,1.0,NaN,11.46,1,0,367.00,291.56
1898,26.821589,86.576370,NaN,0.39,0.36,2019-03-18,0716,N,VIIRS,50,1.0,NaN,4.92,D,0,340.57,303.78
31461,28.918621,81.152863,NaN,0.41,0.60,2021-04-03,1930,N,VIIRS,50,1.0,NaN,0.77,N,0,297.67,286.94
34696,27.873255,84.536003,NaN,0.46,0.39,2016-04-14,0743,N,VIIRS,50,1.0,NaN,3.11,D,0,335.07,303.25
1813,26.803673,86.832352,NaN,0.39,0.36,2012-03-19,0722,N,VIIRS,0,1.0,NaN,3.02,D,0,334.46,306.86
38731,27.781586,82.777931,NaN,0.41,0.45,2016-04-15,1950,N,VIIRS,50,1.0,NaN,2.78,N,0,307.33,293.85
15016,26.864981,86.604698,NaN,0.34,0.56,2014-04-17,1922,N,VIIRS,50,1.0,NaN,0.51,N,0,305.97,290.44
17482,28.633703,81.282280,NaN,0.41,0.37,2021-03-26,2024,N,VIIRS,50,1.0,NaN,14.30,N,0,334.29,303.35
18806,27.491604,84.693542,NaN,0.46,0.39,2021-03-27,0736,N,VIIRS,0,1.0,NaN,2.67,D,0,330.48,302.04
27999,28.057587,82.767792,NaN,0.48,0.65,2012-05-24,0644,N,VIIRS,50,1.0,NaN,3.01,D,0,332.94,293.50

In [36]:
nepal_fire_df = nepal_fire_df.sort_values(by=['acq_date', 'acq_time'])

In [35]:
nepal_fire_df

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight,type,brightness,bright_t31
0,27.592100,87.538500,NaN,1.10,1.10,2000-11-01,0500,Terra,MODIS,55,6.2,NaN,6.20,D,0,306.2,292.1
1,29.100600,81.917000,NaN,1.30,1.10,2000-11-06,0518,Terra,MODIS,87,6.2,NaN,43.00,D,0,330.6,293.7
2,30.088100,81.335800,NaN,1.80,1.30,2000-11-07,0601,Terra,MODIS,58,6.2,NaN,21.10,D,0,308.7,291.2
3,30.084100,81.357000,NaN,1.90,1.30,2000-11-07,0601,Terra,MODIS,37,6.2,NaN,17.10,D,0,306.0,287.4
4,30.106000,81.964700,NaN,2.10,1.40,2000-11-08,0506,Terra,MODIS,64,6.2,NaN,41.60,D,0,315.0,282.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60353,27.125383,84.859642,332.21,0.39,0.36,2021-12-25,0724,N,VIIRS,50,1.0,296.39,2.05,D,0,NaN,NaN
60354,27.128704,84.858986,331.20,0.39,0.36,2021-12-25,0724,N,VIIRS,50,1.0,293.93,2.05,D,0,NaN,NaN
60355,28.698627,80.359848,330.97,0.54,0.42,2021-12-25,0724,N,VIIRS,50,1.0,294.96,8.72,D,0,NaN,NaN
60356,28.820669,80.171555,332.00,0.55,0.43,2021-12-25,0724,N,VIIRS,50,1.0,296.71,3.87,D,0,NaN,NaN
60357,29.633783,81.807281,329.38,0.43,0.46,2021-12-31,0712,N,VIIRS,50,1.0,294.68,3.30,D,0,NaN,NaN

In [37]:
nepal_fire_df['confidence'].nunique()

101

In [38]:
nepal_fire_df['confidence'].unique()

array([ 55,  87,  58,  37,  64,  24,  63,  38,  27,   0,  14,  80,  51,
        35,  17,  47,  43,  72,  71,  70,  46,  48,  34,  53,  88,  85,
        67,  82,  30,  68,  79,  21,  69,  45,  95, 100,  25,  56,  36,
        78,  32,  83,  52,  77,  62,  92,  75,  60,  76,  40,  15,  90,
        59,  39,  74,  89,  94,  57,  33,  49,  12,  29,  41,  54,  20,
        23,  61,  96,  65,  86,  97,  42,  84,  73,  99,  66,  31,  50,
        16,  28,  44,  81,  19,   6,  11,  93,  26,  18,  22,  91,  98,
         9,   7,  13,   8,  10,   5,   3,   4,   2,   1], dtype=int64)

# Brightness #
- brightness: Channel 21/22 brightness temperature of the fire pixel measured in Kelvin.

In [39]:
nepal_fire_df['brightness'].describe()

count    63246.000000
mean       319.393182
std         11.718115
min        300.000000
25%        310.700000
50%        319.400000
75%        325.800000
max        477.200000
Name: brightness, dtype: float64

## Satellite ##

In [40]:
nepal_fire_df['satellite'].unique()

array(['Terra', 'Aqua', 'N'], dtype=object)

In [41]:
nepal_fire_df['instrument'].unique()

array(['MODIS', 'VIIRS'], dtype=object)

## bright_t31 ##
- Channel 31 brightness temperature of the fire pixel measured in Kelvin.

In [42]:
nepal_fire_df['bright_t31'].describe()

count    63246.000000
mean       300.284688
std          8.310892
min        265.200000
25%        293.900000
50%        301.200000
75%        306.700000
max        328.000000
Name: bright_t31, dtype: float64

In [43]:
nepal_fire_df['bright_t31'].unique()

array([292.1, 293.7, 291.2, 287.4, 282.6, 293.4, 289.1, 293.6, 284.1,
       284.5, 287. , 288.6, 288.8, 287.2, 285.3, 286.8, 294.8, 294. ,
       292.7, 280.4, 289.3, 296.8, 281. , 292.4, 292.3, 288.7, 295.7,
       294.4, 295.6, 288.9, 283. , 286.3, 290.7, 282.8, 282.5, 289.7,
       291. , 293.5, 293.2, 291.9, 296.2, 291.5, 295.4, 296.5, 295.2,
       292.8, 298.2, 287.5, 290.4, 288.2, 297.6, 291.4, 297. , 296. ,
       286.2, 293.8, 296.4, 290.1, 289.8, 290.2, 290.9, 297.4, 293. ,
       291.7, 289.6, 291.8, 294.7, 298.5, 285.9, 297.7, 291.6, 290.5,
       289.4, 287.8, 284. , 286.9, 294.5, 281.4, 287.1, 282.1, 283.5,
       282.2, 293.1, 279.3, 278.2, 284.8, 292. , 288.3, 288.5, 286. ,
       287.7, 287.6, 294.6, 283.1, 285. , 292.9, 285.8, 281.1, 291.1,
       285.7, 285.6, 291.3, 286.7, 273. , 293.3, 302.6, 298.9, 277.8,
       286.4, 297.1, 292.5, 289.5, 302.4, 296.1, 294.3, 281.5, 271. ,
       293.9, 290.8, 292.2, 286.6, 301.8, 298.3, 294.1, 275.9, 295.9,
       290.6, 301.7, 298.7, 289.2, 302.2, 303.1, 295.1, 294.9, 300. ,
       300.2, 296.3, 296.9, 295.3, 296.6, 297.2, 299.3, 299.1, 299.5,
       302.1, 304.7, 301.6, 302.7, 301.5, 309.1, 297.8, 298.6, 305.6,
       305.5, 308.1, 311.2, 315.1, 307. , 305.2, 299.8, 300.6, 300.7,
       300.5, 289. , 301.9, 300.9, 303.2, 303.7, 285.2, 299.6, 300.4,
       303.6, 305.1, 304.8, 307.7, 307.8, 303.3, 304.3, 289.9, 301.3,
       299.7, 306. , 305.4, 303.8, 290.3, 302. , 303. , 304.5, 307.3,
       304.6, 280.1, 297.9, 301.4, 300.3, 301.2, 305.8, 302.9, 305. ,
       300.8, 302.8, 305.7, 304.1, 303.5, 304.2, 302.5, 304.9, 299. ,
       300.1, 299.2, 301.1, 307.2, 311.3, 311. , 308.5, 310.4, 311.6,
       309.5, 307.4, 304.4, 299.9, 306.8, 306.7, 307.1, 306.6, 305.9,
       301. , 306.1, 303.9, 292.6, 290. , 294.2, 310.5, 308. , 308.7,
       306.9, 304. , 298.1, 310.2, 311.5, 307.6, 306.5, 311.4, 308.4,
       307.5, 309.7, 310.8, 295.8, 285.5, 282.4, 302.3, 305.3, 306.4,
       307.9, 309. , 311.9, 306.3, 308.2, 310.1, 308.3, 309.2, 309.3,
       313.3, 312.4, 310.6, 308.6, 309.6, 309.4, 310. , 313.6, 312. ,
       309.9, 312.2, 295.5, 303.4, 296.7, 297.3, 297.5, 295. , 298.8,
       288.4, 298.4, 306.2, 311.1, 310.7, 308.9, 312.5, 312.1, 316.1,
       315. , 314. , 315.8, 313.5, 310.9, 311.7, 313.9, 309.8, 283.7,
       272.6, 268.7, 286.1, 269. , 284.9, 281.2, 274.1, 283.4, 279.8,
       278.5, 281.8, 270.4, 279.4, 277.3, 276.9, 283.2, 275.4, 284.3,
       281.7, 277. , 278.8, 282.9, 287.3, 276.5, 279.7, 280.8, 287.9,
       274.6, 285.4, 283.6, 284.7, 286.5, 298. , 299.4, 275.2, 311.8,
       288.1, 273.5, 270.7, 271.7, 284.4, 277.5, 280.6, 281.6, 284.2,
       281.3, 284.6, 280.5, 277.6, 283.8, 282. , 276.6, 277.7, 276.8,
       273.9, 282.7, 288. , 313.2, 281.9, 277.9, 313.4, 312.3, 308.8,
       312.6, 312.9, 280. , 315.6, 314.4, 314.9, 312.7, 314.3, 313.8,
       310.3, 318.9, 315.2, 317.4, 312.8, 314.7, 314.6, 314.8, 313.1,
       317.3, 314.1, 314.2, 320.3, 319.1, 314.5, 315.4, 279. , 313. ,
       313.7, 316. , 316.2, 318.1, 317.6, 316.5, 316.3, 317.2, 266.5,
       279.1, 285.1, 280.2, 278.1, 282.3, 279.6, 279.5, 273.3, 275.8,
       277.4, 271.6, 280.3, 283.3, 274.2, 275.7, 272.7, 278.9, 279.2,
       268.8, 267.8, 266.1, 275.6, 319.4, 315.9, 316.7, 315.7, 316.4,
       315.5, 269.5, 278.3, 283.9, 275.3, 279.9, 280.9, 317.1, 317.8,
       316.8, 316.9, 276.2, 277.1, 276.7, 318.2, 318.4, 320.7, 318.5,
       319. , 315.3, 318.6, 317. , 319.9, 272.9, 271.1, 276. , 276.3,
       280.7, 273.6, 268.4, 271.2, 272.1, 269.1, 276.4, 276.1, 274.3,
       272.2, 271.5, 273.1, 318. , 319.8, 317.9, 318.8, 275.5, 278.6,
       278. , 270.5, 271.4, 274.4, 270.2, 274.5, 271.9, 277.2, 318.7,
       316.6, 317.5, 278.7, 275.1, 273.4, 270.9, 273.7, 274.8, 272.5,
       278.4, 272.3, 265.2, 270.8, 274.9, 268.2, 269.9, 268.3, 317.7,
       319.3, 318.3, 321.3, 320.8, 321.4, 319.5, 319.2, 321.1, 319.6,
       322.9, 324.7, 324.4, 272.4, 270. , 275. ,   nan, 272.8, 320.4,
       321.5, 269.7, 269.6, 320.2, 323.3, 320. , 321.2, 273.8, 274. ,
       269.8, 271.8, 266.8, 268.1, 266.2, 267.9, 328. , 320.6, 321.7,
       321.6, 319.7, 267.7, 266.9, 273.2, 268.9, 272. , 320.5, 267.1,
       265.9, 270.3, 265.4, 266.4, 265.6, 320.1, 321.9, 323.6])

## frp ##
- Fire Radiative Power depicts the pixel-integrated fire radiative power in MW (megawatts).

In [44]:
nepal_fire_df['frp'].describe()

count    363963.000000
mean          6.795216
std          17.165953
min           0.000000
25%           1.400000
50%           3.140000
75%           7.050000
max        2479.900000
Name: frp, dtype: float64

## type ##
- Inferred hot spot type
  - 0 = presumed vegetation fire
  - 1 = active volcano
  - 2 = other static land source
  - 3 = offshore

In [45]:
nepal_fire_df['type'].unique()

array([0, 3, 2], dtype=int64)

## Confidence ##
- This value is based on a collection of intermediate algorithm quantities used in the detection process. 
- It is intended to help users gauge the quality of individual hotspot/fire pixels. 
- Confidence estimates range between 0 and 100% and are assigned one of the three fire classes
  - low-confidence fire
  - nominal-confidence fire
  - high-confidence fire).

In [46]:
nepal_fire_df['confidence'].unique()

array([ 55,  87,  58,  37,  64,  24,  63,  38,  27,   0,  14,  80,  51,
        35,  17,  47,  43,  72,  71,  70,  46,  48,  34,  53,  88,  85,
        67,  82,  30,  68,  79,  21,  69,  45,  95, 100,  25,  56,  36,
        78,  32,  83,  52,  77,  62,  92,  75,  60,  76,  40,  15,  90,
        59,  39,  74,  89,  94,  57,  33,  49,  12,  29,  41,  54,  20,
        23,  61,  96,  65,  86,  97,  42,  84,  73,  99,  66,  31,  50,
        16,  28,  44,  81,  19,   6,  11,  93,  26,  18,  22,  91,  98,
         9,   7,  13,   8,  10,   5,   3,   4,   2,   1], dtype=int64)

In [47]:
nepal_fire_df.columns

Index(['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date',
       'acq_time', 'satellite', 'instrument', 'confidence', 'version',
       'bright_t31', 'frp', 'daynight', 'type', 'bright_ti4', 'bright_ti5'],
      dtype='object')

## Extracting few main feautures from the dataset ##

In [48]:
daily_fires_df = nepal_fire_df.groupby(
            ['latitude', 'longitude', 'acq_date', 'satellite', 'instrument', 'frp', 'type', 'bright_t31']).confidence.max().reset_index()

In [49]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence
0,26.3775,87.3273,2020-11-07,Aqua,MODIS,7.0,0,301.3,57
1,26.4124,87.2421,2019-02-04,Aqua,MODIS,6.7,0,297.4,60
2,26.4171,87.5787,2018-03-06,Terra,MODIS,19.3,0,303.1,80
3,26.4265,87.5735,2013-02-26,Aqua,MODIS,4.8,0,302.9,43
4,26.4285,87.2503,2015-03-21,Terra,MODIS,7.0,0,303.1,62
...,...,...,...,...,...,...,...,...,...
63241,30.2113,81.9902,2012-06-29,Aqua,MODIS,10.3,0,306.9,56
63242,30.2321,82.0426,2002-10-22,Aqua,MODIS,13.1,0,286.1,41
63243,30.2455,81.6329,2003-12-14,Aqua,MODIS,8.2,0,289.2,37
63244,30.2470,81.6431,2003-12-14,Aqua,MODIS,10.0,0,286.7,58
63245,30.2669,81.4897,2016-12-10,Aqua,MODIS,6.7,0,283.3,28

In [50]:
daily_fires_df = daily_fires_df[daily_fires_df.confidence >= 50]

In [51]:
daily_fires_df['confidence'].unique()

array([ 57,  60,  80,  62,  81,  64,  63,  78,  56,  95,  73,  69,  58,
        86,  66,  77,  51,  67,  70,  50,  52,  82,  55,  59,  97,  53,
        74,  75,  71,  72,  54,  87,  76,  99,  85,  61,  68,  65,  88,
       100,  84,  79,  83,  92,  89,  94,  90,  91,  98,  96,  93],
      dtype=int64)

In [52]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence
0,26.3775,87.3273,2020-11-07,Aqua,MODIS,7.0,0,301.3,57
1,26.4124,87.2421,2019-02-04,Aqua,MODIS,6.7,0,297.4,60
2,26.4171,87.5787,2018-03-06,Terra,MODIS,19.3,0,303.1,80
4,26.4285,87.2503,2015-03-21,Terra,MODIS,7.0,0,303.1,62
5,26.4309,87.2452,2011-04-24,Terra,MODIS,43.0,0,298.4,81
...,...,...,...,...,...,...,...,...,...
63238,30.1793,80.8618,2016-12-16,Terra,MODIS,30.7,0,288.9,86
63239,30.1846,80.8731,2016-12-15,Aqua,MODIS,31.6,0,272.1,56
63240,30.1850,82.0371,2011-10-18,Terra,MODIS,26.2,0,287.2,85
63241,30.2113,81.9902,2012-06-29,Aqua,MODIS,10.3,0,306.9,56
63244,30.2470,81.6431,2003-12-14,Aqua,MODIS,10.0,0,286.7,58

In [53]:
daily_fires_df['acq_date'].min()

'2000-11-01'

In [54]:
daily_fires_df['acq_date'].max()

'2021-12-25'

In [55]:
daily_fires_df.describe()

,latitude,longitude,frp,type,bright_t31,confidence
count,46050.000000,46050.000000,46050.000000,46050.000000,46050.000000,46050.000000
mean,28.137238,83.213983,23.508471,0.000391,301.055568,69.534853
std,0.749241,2.092343,41.053802,0.027958,8.167598,12.234586
min,26.377500,80.031500,0.000000,0.000000,265.200000,50.000000
25%,27.536300,81.487125,9.500000,0.000000,294.825000,60.000000
50%,28.122900,82.706600,14.200000,0.000000,302.000000,69.000000
75%,28.728400,84.811100,24.300000,0.000000,307.300000,78.000000
max,30.247000,88.146000,2479.900000,2.000000,328.000000,100.000000

In [56]:
daily_fires_df['acq_date'] = pd.to_datetime(daily_fires_df['acq_date'])

C:\Users\Sawan\AppData\Local\Temp\ipykernel_19268\1911553507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daily_fires_df['acq_date'] = pd.to_datetime(daily_fires_df['acq_date'])

In [57]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence
0,26.3775,87.3273,2020-11-07,Aqua,MODIS,7.0,0,301.3,57
1,26.4124,87.2421,2019-02-04,Aqua,MODIS,6.7,0,297.4,60
2,26.4171,87.5787,2018-03-06,Terra,MODIS,19.3,0,303.1,80
4,26.4285,87.2503,2015-03-21,Terra,MODIS,7.0,0,303.1,62
5,26.4309,87.2452,2011-04-24,Terra,MODIS,43.0,0,298.4,81
...,...,...,...,...,...,...,...,...,...
63238,30.1793,80.8618,2016-12-16,Terra,MODIS,30.7,0,288.9,86
63239,30.1846,80.8731,2016-12-15,Aqua,MODIS,31.6,0,272.1,56
63240,30.1850,82.0371,2011-10-18,Terra,MODIS,26.2,0,287.2,85
63241,30.2113,81.9902,2012-06-29,Aqua,MODIS,10.3,0,306.9,56
63244,30.2470,81.6431,2003-12-14,Aqua,MODIS,10.0,0,286.7,58

In [58]:
daily_fires_df['year'] = daily_fires_df.acq_date.dt.year

C:\Users\Sawan\AppData\Local\Temp\ipykernel_19268\2902059493.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daily_fires_df['year'] = daily_fires_df.acq_date.dt.year

In [59]:
daily_fires_df['month'] = daily_fires_df.acq_date.dt.month

C:\Users\Sawan\AppData\Local\Temp\ipykernel_19268\1262889700.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daily_fires_df['month'] = daily_fires_df.acq_date.dt.month

In [60]:
daily_fires_df

,latitude,longitude,acq_date,satellite,instrument,frp,type,bright_t31,confidence,year,month
0,26.3775,87.3273,2020-11-07,Aqua,MODIS,7.0,0,301.3,57,2020,11
1,26.4124,87.2421,2019-02-04,Aqua,MODIS,6.7,0,297.4,60,2019,2
2,26.4171,87.5787,2018-03-06,Terra,MODIS,19.3,0,303.1,80,2018,3
4,26.4285,87.2503,2015-03-21,Terra,MODIS,7.0,0,303.1,62,2015,3
5,26.4309,87.2452,2011-04-24,Terra,MODIS,43.0,0,298.4,81,2011,4
...,...,...,...,...,...,...,...,...,...,...,...
63238,30.1793,80.8618,2016-12-16,Terra,MODIS,30.7,0,288.9,86,2016,12
63239,30.1846,80.8731,2016-12-15,Aqua,MODIS,31.6,0,272.1,56,2016,12
63240,30.1850,82.0371,2011-10-18,Terra,MODIS,26.2,0,287.2,85,2011,10
63241,30.2113,81.9902,2012-06-29,Aqua,MODIS,10.3,0,306.9,56,2012,6
63244,30.2470,81.6431,2003-12-14,Aqua,MODIS,10.0,0,286.7,58,2003,12

In [61]:
daily_fires_df['acq_date'].min()

Timestamp('2000-11-01 00:00:00')

In [62]:
daily_fires_df['acq_date'].max()

Timestamp('2021-12-25 00:00:00')

In [63]:
daily_fires_df.to_csv('nepal_daily_fire_2000_2020.csv', index=False)
#ca_daily_fire.to_csv('ca_daily_fire_2012_2020.csv.gz', index=False, compression='gzip')

In [64]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 8E69-9D46

 Directory of C:\Users\Sawan\Documents\dataset

14-03-2023  11:35    <DIR>          .
14-03-2023  11:34    <DIR>          ..
13-03-2023  21:08    <DIR>          modis
14-03-2023  11:35         2,855,490 nepal_daily_fire_2000_2020.csv
13-03-2023  21:20    <DIR>          viirs_snnp
               1 File(s)      2,855,490 bytes
               4 Dir(s)  56,459,845,632 bytes free